import { BotanicalEntity, ClassicalYoga } from '../src/types.js';

export const BOTANICAL_DATABASE: BotanicalEntity[] = [
  {
    id: 'ashwagandha',
    sanskritName: 'Ashwagandha',
    hindiName: 'अश्वगंधा',
    commonName: 'Indian Ginseng / Winter Cherry',
    botanicalName: 'Withania somnifera (L.) Dunal',
    family: 'Solanaceae',
    plantPartsUsed: ['Root', 'Leaves'],
    pharmacopoeiaRef: 'Ayurvedic Pharmacopoeia of India (API) Part I, Vol. I, Page 19',
    classicalYogas: ['Ashwagandharishta', 'Ashwagandhadi Lehya', 'Chyawanprash', 'Mahanarayana Taila'],
    indications: ['Sandhivata (Osteoarthritis)', 'Kshaya (Debility)', 'Balya (Strength promoter)', 'Rasayana (Rejuvenation)', 'Nidranasha (Insomnia)'],
    traditionalKnowledgeSummary: 'Referenced across Charaka Samhita (Sutrasthana 4, Chikitsasthana 1) and Sushruta Samhita as Balya, Rasayana, and Vata-shamaka. Extensive documentation in TKDL.',
    tkdlReference: 'TKDL Identifier: CS-194 / AH-312 (Withania somnifera in joint and cognitive formulations)',
    famousRevocationCase: 'Referenced in multiple third-party pre-grant oppositions against uninventive cosmetic/anti-stress mixtures.'
  },
  {
    id: 'haridra',
    sanskritName: 'Haridra',
    hindiName: 'हल्दी',
    commonName: 'Turmeric',
    botanicalName: 'Curcuma longa L.',
    family: 'Zingiberaceae',
    plantPartsUsed: ['Rhizome'],
    pharmacopoeiaRef: 'Ayurvedic Pharmacopoeia of India (API) Part I, Vol. I, Page 45',
    classicalYogas: ['Haridra Khanda', 'Nisha Amalaki', 'Chandraprabha Vati', 'Jatyadi Taila'],
    indications: ['Vranaropana (Wound healing)', 'Kustha (Skin disorders)', 'Prameha (Metabolic disorders)', 'Shothahara (Anti-inflammatory)'],
    traditionalKnowledgeSummary: 'Documented in Charaka Samhita (Chikitsasthana 3) and Bhaishajya Ratnavali for wound healing, metabolic disorders, and inflammatory relief.',
    tkdlReference: 'TKDL Identifier: CS-402 / BR-118 (Curcuma longa topical & systemic formulations)',
    famousRevocationCase: 'USPTO Patent No. 5,401,504 for "Use of Turmeric in Wound Healing" revoked following challenge by CSIR using Sanskrit ancient texts.'
  },
  {
    id: 'guggulu',
    sanskritName: 'Guggulu',
    hindiName: 'गुग्गुल',
    commonName: 'Indian Bdellium / Guggul',
    botanicalName: 'Commiphora mukul (Stocks) Hook. / Commiphora wightii',
    family: 'Burseraceae',
    plantPartsUsed: ['Exudate / Oleo-gum-resin'],
    pharmacopoeiaRef: 'Ayurvedic Pharmacopoeia of India (API) Part I, Vol. I, Page 43',
    classicalYogas: ['Yogaraja Guggulu', 'Kaishore Guggulu', 'Triphala Guggulu', 'Simhanada Guggulu'],
    indications: ['Amavata (Rheumatoid arthritis)', 'Sandhivata (Osteoarthritis)', 'Medoroga (Obesity / Dyslipidemia)', 'Vatarakta (Gout)'],
    traditionalKnowledgeSummary: 'Celebrated in Sushruta Samhita (Sutrasthana 15) for deep tissue scraping (Lekhana) and clearing Vata-Kapha obstructions.',
    tkdlReference: 'TKDL Identifier: SS-089 (Commiphora mukul purified formulations)',
    famousRevocationCase: 'EPO application on guggulsterone fractions faced TKDL third-party submissions proving prior classical use for lipid balance.'
  },
  {
    id: 'guduchi',
    sanskritName: 'Guduchi',
    hindiName: 'गिलोय / अमृता',
    commonName: 'Heart-leaved Moonseed / Giloy',
    botanicalName: 'Tinospora cordifolia (Willd.) Miers',
    family: 'Menispermaceae',
    plantPartsUsed: ['Stem'],
    pharmacopoeiaRef: 'Ayurvedic Pharmacopoeia of India (API) Part I, Vol. I, Page 41',
    classicalYogas: ['Amritarishta', 'Samsamani Vati', 'Guduchi Satva', 'Chyawanprash'],
    indications: ['Jvara (Fever)', 'Rasayana (Immunomodulation)', 'Prameha (Diabetes)', 'Vatarakta (Gout)', 'Kamala (Liver conditions)'],
    traditionalKnowledgeSummary: 'Revered in Charaka Samhita as Vayasthapana (youth sustainer) and Dahaprashamana (alleviator of burning sensation).',
    tkdlReference: 'TKDL Identifier: CS-511 (Tinospora cordifolia extract preparations)'
  },
  {
    id: 'brahmi',
    sanskritName: 'Brahmi',
    hindiName: 'ब्राह्मी',
    commonName: 'Water Hyssop / Bacopa',
    botanicalName: 'Bacopa monnieri (L.) Wettst.',
    family: 'Plantaginaceae / Scrophulariaceae',
    plantPartsUsed: ['Whole plant'],
    pharmacopoeiaRef: 'Ayurvedic Pharmacopoeia of India (API) Part I, Vol. II, Page 25',
    classicalYogas: ['Brahmi Ghrita', 'Brahmi Vati', 'Saraswatarishta'],
    indications: ['Medhya (Nootropic / Cognitive booster)', 'Smritiprada (Memory enhancer)', 'Unmada (Mental clarity)', 'Apasmara (Nervous equilibrium)'],
    traditionalKnowledgeSummary: 'Foundational Medhya Rasayana in Charaka Samhita (Chikitsasthana 1) for enhancing Dhi (acquisition), Dhriti (retention), and Smriti (recall).',
    tkdlReference: 'TKDL Identifier: CS-310 (Bacopa monnieri cognitive formulations)'
  },
  {
    id: 'shatavari',
    sanskritName: 'Shatavari',
    hindiName: 'शतावरी',
    commonName: 'Wild Asparagus',
    botanicalName: 'Asparagus racemosus Willd.',
    family: 'Asparagaceae / Liliaceae',
    plantPartsUsed: ['Tuberous root'],
    pharmacopoeiaRef: 'Ayurvedic Pharmacopoeia of India (API) Part I, Vol. IV, Page 108',
    classicalYogas: ['Shatavari Ghritha', 'Shatavaryadi Churna', 'Narayana Taila'],
    indications: ['Stanya-janana (Galactagogue)', 'Rasayana', 'Pitta-shamaka (Cooling tonic)', 'Shukrala (Reproductive support)'],
    traditionalKnowledgeSummary: 'Documented in Ashtanga Hridaya and Charaka Samhita for female endocrine vitality, mucosal soothing, and general strength.',
    tkdlReference: 'TKDL Identifier: AH-405 (Asparagus racemosus preparations)'
  },
  {
    id: 'tulsi',
    sanskritName: 'Tulasi',
    hindiName: 'तुलसी',
    commonName: 'Holy Basil',
    botanicalName: 'Ocimum sanctum L. / Ocimum tenuiflorum L.',
    family: 'Lamiaceae',
    plantPartsUsed: ['Leaves', 'Whole plant', 'Seeds'],
    pharmacopoeiaRef: 'Ayurvedic Pharmacopoeia of India (API) Part I, Vol. II, Page 143',
    classicalYogas: ['Tribhuvankirti Rasa', 'Surasadi Taila', 'Kasahara Kwatha'],
    indications: ['Shvasahara (Bronchial ease)', 'Kaphahara (Decongestant)', 'Vishaghna (Detoxification)', 'Hikka (Hiccups)'],
    traditionalKnowledgeSummary: 'Cited in Bhavaprakasha Nighantu and Charaka Samhita as Surasa group, potent against pulmonary and microbial afflictions.',
    tkdlReference: 'TKDL Identifier: BPN-082 (Ocimum sanctum respiratory formulations)'
  },
  {
    id: 'amalaki',
    sanskritName: 'Amalaki',
    hindiName: 'आंवला',
    commonName: 'Indian Gooseberry / Amla',
    botanicalName: 'Phyllanthus emblica L. (syn. Emblica officinalis)',
    family: 'Phyllanthaceae / Euphorbiaceae',
    plantPartsUsed: ['Dried Fruit Pericarp', 'Fresh Fruit'],
    pharmacopoeiaRef: 'Ayurvedic Pharmacopoeia of India (API) Part I, Vol. I, Page 5',
    classicalYogas: ['Chyawanprash', 'Triphala Churna', 'Dhatri Lauha', 'Brahma Rasayana'],
    indications: ['Rasayana (Antioxidant rejuvenation)', 'Chakshushya (Ocular health)', 'Vayasthapana (Anti-aging)', 'Prameha (Glycemic support)'],
    traditionalKnowledgeSummary: 'Chief ingredient of Chyawanprash in Charaka Samhita; renowned for containing five of the six tastes (except Lavana).',
    tkdlReference: 'TKDL Identifier: CS-004 (Phyllanthus emblica longevity compounds)'
  },
  {
    id: 'pippali',
    sanskritName: 'Pippali',
    hindiName: 'पीपल / पिप्पली',
    commonName: 'Long Pepper',
    botanicalName: 'Piper longum L.',
    family: 'Piperaceae',
    plantPartsUsed: ['Dried spikes / Root (Pippalimula)'],
    pharmacopoeiaRef: 'Ayurvedic Pharmacopoeia of India (API) Part I, Vol. IV, Page 91',
    classicalYogas: ['Trikatu Churna', 'Sitopaladi Churna', 'Pippalyasava', 'Vardhamana Pippali'],
    indications: ['Kasa-Shvasa (Cough & dyspnea)', 'Deepana-Pachana (Digestive fire enhancer)', 'Yogavahi (Bioenhancer / Bioavailability promoter)'],
    traditionalKnowledgeSummary: 'Standard classical bioavailability enhancer (Yogavahi) documented in Sharangadhara Samhita and Charaka Samhita.',
    tkdlReference: 'TKDL Identifier: SH-124 (Piper longum bioenhancement mixtures)'
  },
  {
    id: 'shallaki',
    sanskritName: 'Shallaki',
    hindiName: 'शल्लकी / सलाई',
    commonName: 'Indian Olibanum / Boswellia',
    botanicalName: 'Boswellia serrata Roxb. ex Colebr.',
    family: 'Burseraceae',
    plantPartsUsed: ['Exudate / Gum-resin'],
    pharmacopoeiaRef: 'Ayurvedic Pharmacopoeia of India (API) Part I, Vol. III, Page 203',
    classicalYogas: ['Shallaki Vati', 'Jirakadi Modaka', 'Maha-yogaraja Guggulu'],
    indications: ['Sandhivata (Joint inflammation)', 'Amavata (Rheumatoid aches)', 'Purishavirajaniya (Colitis support)'],
    traditionalKnowledgeSummary: 'Cited in Sushruta Samhita and Bhavaprakasha as potent analgesic and anti-inflammatory resin without gastric mucosal harm.',
    tkdlReference: 'TKDL Identifier: SS-220 (Boswellia serrata arthritis preparations)'
  },
  {
    id: 'nimba',
    sanskritName: 'Nimba',
    hindiName: 'नीम',
    commonName: 'Margosa / Neem',
    botanicalName: 'Azadirachta indica A. Juss.',
    family: 'Meliaceae',
    plantPartsUsed: ['Leaf', 'Bark', 'Seed Oil', 'Flower'],
    pharmacopoeiaRef: 'Ayurvedic Pharmacopoeia of India (API) Part I, Vol. II, Page 115',
    classicalYogas: ['Nimbadi Churna', 'Pancha-tikta Ghrita', 'Jatyadi Taila', 'Nimba Taila'],
    indications: ['Krimighna (Antimicrobial / Anthelmintic)', 'Kusthaghna (Dermatological)', 'Vranashodhana (Wound cleansing)'],
    traditionalKnowledgeSummary: 'Prominent Bitter (Tikta) tonic in Charaka Samhita Sutrasthana 27 and Sushruta Samhita for purifying blood and tissue.',
    tkdlReference: 'TKDL Identifier: CS-622 (Azadirachta indica antifungal & pesticidal preparations)',
    famousRevocationCase: 'EPO Patent No. 436257 on fungicidal effect of neem oil revoked after CSIR/India submitted ancient Sanskrit classical texts proving prior art.'
  },
  {
    id: 'haritaki',
    sanskritName: 'Haritaki',
    hindiName: 'हरीतकी',
    commonName: 'Chebulic Myrobalan',
    botanicalName: 'Terminalia chebula Retz.',
    family: 'Combretaceae',
    plantPartsUsed: ['Dried mature fruit'],
    pharmacopoeiaRef: 'API Part I Vol I pg 47',
    classicalYogas: ['Triphala Churna', 'Abhayarishta', 'Agastya Haritaki Rasayana', 'Pathyadi Kwatha'],
    indications: ['Vibandha (Constipation)', 'Deepana-Pachana', 'Rasayana', 'Medhya', 'Chakshushya'],
    traditionalKnowledgeSummary: 'Called Pathya (wholesome in all conditions) in Charaka Samhita. Listed among Triphala since Sushruta Samhita. Bhavaprakasha designates it as foremost among Rasayanas.',
    tkdlReference: 'TKDL Identifier: CS-009 (Terminalia chebula digestive and longevity formulations)'
  },
  {
    id: 'bibhitaki',
    sanskritName: 'Bibhitaki',
    hindiName: 'बहेड़ा',
    commonName: 'Belleric Myrobalan',
    botanicalName: 'Terminalia bellirica (Gaertn.) Roxb.',
    family: 'Combretaceae',
    plantPartsUsed: ['Dried mature fruit pericarp'],
    pharmacopoeiaRef: 'API Part I Vol I pg 23',
    classicalYogas: ['Triphala Churna', 'Triphala Guggulu', 'Phalatrikadi Kwatha'],
    indications: ['Kasahara (Antitussive)', 'Keshya (Hair tonic)', 'Krimighna', 'Prameha'],
    traditionalKnowledgeSummary: 'Charaka Samhita classifies Bibhitaki in Jvarahara and Kasahara Mahakashaya groups. Dried fruit rind used in respiratory and metabolic formulations.',
    tkdlReference: 'TKDL Identifier: CS-012 (Terminalia bellirica respiratory preparations)'
  },
  {
    id: 'yashtimadhu',
    sanskritName: 'Yashtimadhu',
    hindiName: 'मुलेठी',
    commonName: 'Licorice / Liquorice',
    botanicalName: 'Glycyrrhiza glabra L.',
    family: 'Fabaceae',
    plantPartsUsed: ['Root', 'Stolon'],
    pharmacopoeiaRef: 'API Part I Vol I pg 128',
    classicalYogas: ['Yashtimadhu Churna', 'Sitopaladi Churna', 'Ashwagandharishta', 'Eladi Vati'],
    indications: ['Kasahara (Antitussive)', 'Svarya (Voice enhancer)', 'Sandhaniya (Fracture healing)', 'Pittashamaka'],
    traditionalKnowledgeSummary: 'Listed in Charaka Samhita Sutrasthana Chapter 4 among Kanthya (throat-soothing) and Jivaniya (vitalizing) groups. EU HMPC monograph exists for traditional use.',
    tkdlReference: 'TKDL Identifier: CS-187 (Glycyrrhiza glabra respiratory and digestive formulations)'
  },
  {
    id: 'arjuna',
    sanskritName: 'Arjuna',
    hindiName: 'अर्जुन',
    commonName: 'Arjuna Tree',
    botanicalName: 'Terminalia arjuna (Roxb.) Wight & Arn.',
    family: 'Combretaceae',
    plantPartsUsed: ['Stem bark'],
    pharmacopoeiaRef: 'API Part I Vol I pg 17',
    classicalYogas: ['Arjunarishta', 'Arjuna Kshirapaka', 'Hridayarnava Rasa'],
    indications: ['Hridya (Cardiotonic)', 'Raktapitta (Hemostatic)', 'Prameha', 'Medohara (Lipid-lowering)'],
    traditionalKnowledgeSummary: 'Vagbhata (Ashtanga Hridaya) and Charaka describe Arjuna bark as the foremost Hridya (cardiac tonic). Multiple clinical trial patents filed globally on arjunic acid.',
    tkdlReference: 'TKDL Identifier: CS-015 (Terminalia arjuna cardiovascular preparations)',
    famousRevocationCase: 'Several international patents on Terminalia arjuna bark extract cardioprotective uses challenged using TKDL classical evidence.'
  },
  {
    id: 'bala',
    sanskritName: 'Bala',
    hindiName: 'बला',
    commonName: 'Country Mallow',
    botanicalName: 'Sida cordifolia L.',
    family: 'Malvaceae',
    plantPartsUsed: ['Root', 'Whole plant'],
    pharmacopoeiaRef: 'API Part I Vol II pg 18',
    classicalYogas: ['Bala Taila', 'Dhanvantara Taila', 'Mahanarayana Taila', 'Chyawanprash'],
    indications: ['Balya (Strength promoter)', 'Vata-shamaka', 'Prameha', 'Shukrala'],
    traditionalKnowledgeSummary: 'Charaka Samhita classifies Bala in Balya and Brimhaniya Mahakashaya. Contains ephedrine alkaloids — subject to import restrictions in USA, EU, and Australia.',
    tkdlReference: 'TKDL Identifier: CS-022 (Sida cordifolia strengthening formulations)'
  },
  {
    id: 'punarnava',
    sanskritName: 'Punarnava',
    hindiName: 'पुनर्नवा',
    commonName: 'Spreading Hogweed / Red Spiderling',
    botanicalName: 'Boerhavia diffusa L.',
    family: 'Nyctaginaceae',
    plantPartsUsed: ['Root', 'Whole plant'],
    pharmacopoeiaRef: 'API Part I Vol III pg 156',
    classicalYogas: ['Punarnavadi Mandura', 'Punarnavadi Kwatha', 'Punarnavasava', 'Chyawanprash'],
    indications: ['Shothaghna (Anti-edema)', 'Mutrala (Diuretic)', 'Panduhara (Anti-anemic)', 'Rasayana'],
    traditionalKnowledgeSummary: 'Named Punarnava (that which renews the body) in Charaka Samhita. Celebrated for Shotha (edema) reduction and nephroprotective actions.',
    tkdlReference: 'TKDL Identifier: CS-155 (Boerhavia diffusa anti-edema formulations)'
  },
  {
    id: 'gokshura',
    sanskritName: 'Gokshura',
    hindiName: 'गोखरू',
    commonName: 'Puncture Vine / Caltrops',
    botanicalName: 'Tribulus terrestris L.',
    family: 'Zygophyllaceae',
    plantPartsUsed: ['Fruit', 'Whole plant'],
    pharmacopoeiaRef: 'API Part I Vol I pg 39',
    classicalYogas: ['Gokshuradi Guggulu', 'Gokshuradi Churna', 'Chandraprabha Vati', 'Dashamularishta'],
    indications: ['Mutrala (Diuretic)', 'Ashmariharana (Lithotriptic)', 'Vrushya (Aphrodisiac)', 'Balya'],
    traditionalKnowledgeSummary: 'Charaka Samhita lists Gokshura in Mutravirechaniya (diuretic) Mahakashaya. Major commercial supplement for sports nutrition globally; regulatory classification disputes between food and drug in multiple jurisdictions.',
    tkdlReference: 'TKDL Identifier: CS-038 (Tribulus terrestris urological formulations)'
  },
  {
    id: 'chitraka',
    sanskritName: 'Chitraka',
    hindiName: 'चित्रक',
    commonName: 'Ceylon Leadwort',
    botanicalName: 'Plumbago zeylanica L.',
    family: 'Plumbaginaceae',
    plantPartsUsed: ['Root'],
    pharmacopoeiaRef: 'API Part I Vol I pg 31',
    classicalYogas: ['Chitrakadi Vati', 'Yogaraja Guggulu', 'Agnitundi Vati'],
    indications: ['Deepana (Appetite stimulant)', 'Pachana (Digestive)', 'Arshoghna (Anti-hemorrhoidal)', 'Gulmahara'],
    traditionalKnowledgeSummary: 'Charaka Samhita describes Chitraka as foremost Deepaniya (appetizer). Contains plumbagin — a bioactive with significant patent filings for anticancer activity.',
    tkdlReference: 'TKDL Identifier: CS-030 (Plumbago zeylanica digestive preparations)'
  },
  {
    id: 'vidanga',
    sanskritName: 'Vidanga',
    hindiName: 'वायविडंग',
    commonName: 'False Black Pepper / Vidanga',
    botanicalName: 'Embelia ribes Burm.f.',
    family: 'Primulaceae',
    plantPartsUsed: ['Dried fruit'],
    pharmacopoeiaRef: 'API Part I Vol I pg 126',
    classicalYogas: ['Vidangadi Churna', 'Yogaraja Guggulu', 'Krimighna Vati'],
    indications: ['Krimighna (Anthelmintic)', 'Deepana', 'Medohara', 'Kushthaghna'],
    traditionalKnowledgeSummary: 'Charaka Samhita designates Vidanga as foremost Krimighna (anthelmintic). Embelin, its chief bioactive, is subject to multiple pharmaceutical patents.',
    tkdlReference: 'TKDL Identifier: CS-123 (Embelia ribes anthelmintic preparations)'
  },
  {
    id: 'bhringaraja',
    sanskritName: 'Bhringaraja',
    hindiName: 'भृंगराज',
    commonName: 'False Daisy',
    botanicalName: 'Eclipta alba (L.) Hassk. / Eclipta prostrata',
    family: 'Asteraceae',
    plantPartsUsed: ['Whole plant', 'Leaf', 'Root'],
    pharmacopoeiaRef: 'API Part I Vol II pg 22',
    classicalYogas: ['Bhringaraja Taila', 'Bhringamalakadi Taila', 'Mahabhringaraja Taila', 'Neelibhringadi Taila'],
    indications: ['Keshya (Hair growth)', 'Rasayana', 'Yakrit-uttejaka (Hepatoprotective)', 'Kushtaghna'],
    traditionalKnowledgeSummary: 'Bhavaprakasha Nighantu classifies Bhringaraja as supreme Keshya (hair tonic). Massive cosmetic and hair-care market makes TM Class 3 registrations critical.',
    tkdlReference: 'TKDL Identifier: BPN-045 (Eclipta alba hair and liver formulations)'
  },
  {
    id: 'kumari',
    sanskritName: 'Kumari',
    hindiName: 'घृतकुमारी / एलोवेरा',
    commonName: 'Aloe Vera',
    botanicalName: 'Aloe vera (L.) Burm.f. / Aloe barbadensis Mill.',
    family: 'Asphodelaceae',
    plantPartsUsed: ['Leaf pulp/gel', 'Latex'],
    pharmacopoeiaRef: 'API Part I Vol IV pg 7',
    classicalYogas: ['Kumaryasava', 'Kumari Paka'],
    indications: ['Vranaropana (Wound healing)', 'Yakrit-uttejaka (Hepatoprotective)', 'Raktashodhaka (Blood purifier)', 'Tvachya (Skin health)'],
    traditionalKnowledgeSummary: 'Documented in Bhavaprakasha and Dhanvantari Nighantu. Massive global market spanning food, cosmetic, and pharmaceutical categories with overlapping regulatory classifications in every jurisdiction.',
    tkdlReference: 'TKDL Identifier: BPN-092 (Aloe vera topical and internal preparations)'
  },
  {
    id: 'musta',
    sanskritName: 'Musta',
    hindiName: 'मोथा / नागरमोथा',
    commonName: 'Nutgrass / Nagarmotha',
    botanicalName: 'Cyperus rotundus L.',
    family: 'Cyperaceae',
    plantPartsUsed: ['Rhizome / Tuber'],
    pharmacopoeiaRef: 'API Part I Vol III pg 134',
    classicalYogas: ['Mustadi Churna', 'Mustakarishtam', 'Chandraprabha Vati', 'Chyawanprash'],
    indications: ['Deepana-Pachana', 'Stambhana (Astringent)', 'Grahani (IBS)', 'Jvarahara'],
    traditionalKnowledgeSummary: 'Charaka Samhita lists Musta as foremost Deepaniya-Pachana in multiple Mahakashaya groups. Underexplored patent potential despite extensive traditional documentation.',
    tkdlReference: 'TKDL Identifier: CS-130 (Cyperus rotundus digestive formulations)'
  },
  {
    id: 'jatamansi',
    sanskritName: 'Jatamansi',
    hindiName: 'जटामांसी',
    commonName: 'Indian Spikenard',
    botanicalName: 'Nardostachys jatamansi (D.Don) DC.',
    family: 'Caprifoliaceae',
    plantPartsUsed: ['Rhizome', 'Root'],
    pharmacopoeiaRef: 'API Part I Vol I pg 55',
    classicalYogas: ['Jatamansi Churna', 'Saraswatarishta', 'Brahmi Ghrita'],
    indications: ['Nidrajanana (Sedative)', 'Medhya', 'Manasroga (Psychiatric)', 'Keshya'],
    traditionalKnowledgeSummary: 'Highly valued in Charaka Samhita for Manasroga (mental disorders). Listed in CITES Appendix II — international trade strictly regulated. ABS compliance critical for all commercial utilization.',
    tkdlReference: 'TKDL Identifier: CS-054 (Nardostachys jatamansi neurological preparations)'
  },
  {
    id: 'katuki',
    sanskritName: 'Katuki',
    hindiName: 'कुटकी',
    commonName: 'Kutki / Hellebore',
    botanicalName: 'Picrorhiza kurroa Royle ex Benth.',
    family: 'Plantaginaceae',
    plantPartsUsed: ['Rhizome', 'Root'],
    pharmacopoeiaRef: 'API Part I Vol I pg 63',
    classicalYogas: ['Arogyavardhini Vati', 'Tiktaka Ghrita', 'Katuki Churna'],
    indications: ['Yakrit-uttejaka (Hepatoprotective)', 'Kamala (Jaundice)', 'Jvarahara', 'Krimighna'],
    traditionalKnowledgeSummary: 'Listed in CITES Appendix II due to over-harvesting. Contains picrosides I & II with significant pharmaceutical patent interest for hepatoprotective activity. ABS and sustainability compliance mandatory.',
    tkdlReference: 'TKDL Identifier: CS-062 (Picrorhiza kurroa hepatoprotective preparations)'
  },
  {
    id: 'kapikacchu',
    sanskritName: 'Kapikacchu',
    hindiName: 'कौंच / केवांच',
    commonName: 'Velvet Bean / Cowhage',
    botanicalName: 'Mucuna pruriens (L.) DC.',
    family: 'Fabaceae',
    plantPartsUsed: ['Seed', 'Root'],
    pharmacopoeiaRef: 'API Part I Vol III pg 68',
    classicalYogas: ['Vanari Gutika', 'Musli Pak', 'Kapikacchu Churna'],
    indications: ['Vrishya (Aphrodisiac)', 'Balya', 'Vatahara', 'Kampa (Tremor/Parkinsonism)'],
    traditionalKnowledgeSummary: 'Contains natural L-DOPA — the precursor of dopamine. Creates complex regulatory and IP overlap with pharmaceutical L-DOPA patents for Parkinson\'s disease treatment. Charaka Samhita classifies it as prime Vrishya (aphrodisiac).',
    tkdlReference: 'TKDL Identifier: CS-075 (Mucuna pruriens reproductive and neurological preparations)'
  },
  {
    id: 'manjistha',
    sanskritName: 'Manjistha',
    hindiName: 'मजीठ / मंजिष्ठा',
    commonName: 'Indian Madder',
    botanicalName: 'Rubia cordifolia L.',
    family: 'Rubiaceae',
    plantPartsUsed: ['Root', 'Stem'],
    pharmacopoeiaRef: 'API Part I Vol II pg 106',
    classicalYogas: ['Mahamanjisthadi Kwatha', 'Manjisthadi Taila', 'Ashwagandharishta', 'Chandraprabha Vati'],
    indications: ['Varnya (Complexion enhancer)', 'Raktashodhaka (Blood purifier)', 'Vranaropana (Wound healing)', 'Vishahara (Detoxification)'],
    traditionalKnowledgeSummary: 'Charaka Samhita lists Manjistha in Varnya (complexion-enhancing) Mahakashaya. Major ingredient in skin-care products with TM Class 3 implications.',
    tkdlReference: 'TKDL Identifier: CS-101 (Rubia cordifolia dermatological preparations)'
  },
  {
    id: 'daruharidra',
    sanskritName: 'Daruharidra',
    hindiName: 'दारुहल्दी',
    commonName: 'Indian Barberry / Tree Turmeric',
    botanicalName: 'Berberis aristata DC.',
    family: 'Berberidaceae',
    plantPartsUsed: ['Stem', 'Root', 'Root bark'],
    pharmacopoeiaRef: 'API Part I Vol I pg 33',
    classicalYogas: ['Dasanga Lepa', 'Rasanjana', 'Ashwagandharishta'],
    indications: ['Prameha', 'Netrya (Ophthalmological)', 'Kustha', 'Raktashodhaka'],
    traditionalKnowledgeSummary: 'Rich source of berberine — one of the most heavily patented plant alkaloids globally. Multiple patents on berberine for diabetes (Prameha) and metabolic syndrome challenged using TKDL evidence.',
    tkdlReference: 'TKDL Identifier: CS-033 (Berberis aristata metabolic and ophthalmic preparations)'
  },
  {
    id: 'sunthi',
    sanskritName: 'Sunthi',
    hindiName: 'सोंठ / अदरक',
    commonName: 'Dried Ginger',
    botanicalName: 'Zingiber officinale Roscoe',
    family: 'Zingiberaceae',
    plantPartsUsed: ['Dried rhizome'],
    pharmacopoeiaRef: 'API Part I Vol I pg 113',
    classicalYogas: ['Trikatu Churna', 'Sitopaladi Churna', 'Sunthi Churna', 'Vishwabheshaja'],
    indications: ['Deepana-Pachana (Digestive stimulant)', 'Kasahara (Antitussive)', 'Amapachana (Ama digestion)', 'Shulahara (Analgesic)'],
    traditionalKnowledgeSummary: 'Called Vishwabheshaja (universal medicine) in Ayurvedic literature. Charaka Samhita classifies it in multiple therapeutic groups. Massive global spice trade with GI potential for specific regional varieties.',
    tkdlReference: 'TKDL Identifier: CS-110 (Zingiber officinale digestive and respiratory formulations)'
  },
  {
    id: 'maricha',
    sanskritName: 'Maricha',
    hindiName: 'काली मिर्च',
    commonName: 'Black Pepper',
    botanicalName: 'Piper nigrum L.',
    family: 'Piperaceae',
    plantPartsUsed: ['Dried unripe fruit'],
    pharmacopoeiaRef: 'API Part I Vol III pg 110',
    classicalYogas: ['Trikatu Churna', 'Sitopaladi Churna', 'Panchakola Churna', 'Tribhuvankirti Rasa'],
    indications: ['Deepana (Appetite stimulant)', 'Kasahara', 'Krimighna', 'Yogavahi (Bioenhancer)'],
    traditionalKnowledgeSummary: 'Charaka Samhita Sutrasthana references Maricha in Deepaniya and Shiro-virechaniya groups. Piperine as bioenhancer has extensive patent landscape. Malabar Pepper holds GI #49 registration.',
    tkdlReference: 'TKDL Identifier: CS-102 (Piper nigrum bioenhancer preparations)',
    famousRevocationCase: 'Piperine bioavailability enhancement patents challenged using prior art from Sharangadhara Samhita describing Trikatu as Yogavahi (bioenhancer).'
  },
  {
    id: 'vacha',
    sanskritName: 'Vacha',
    hindiName: 'बच / वच',
    commonName: 'Sweet Flag / Calamus',
    botanicalName: 'Acorus calamus L.',
    family: 'Acoraceae',
    plantPartsUsed: ['Rhizome'],
    pharmacopoeiaRef: 'API Part I Vol I pg 120',
    classicalYogas: ['Vachadi Churna', 'Saraswata Churna', 'Brahmi Ghrita'],
    indications: ['Medhya (Nootropic)', 'Svarya (Voice enhancer)', 'Deepana', 'Unmadahara (Psychiatric)'],
    traditionalKnowledgeSummary: 'Charaka Samhita classifies Vacha in Medhya group. CRITICAL REGULATORY ISSUE: Contains β-asarone — BANNED by US FDA as carcinogenic food additive (21 CFR 189.110). EU restricts β-asarone in food supplements. Export requires calamus oil to contain <0.01% β-asarone (diploid variety).',
    tkdlReference: 'TKDL Identifier: CS-119 (Acorus calamus cognitive preparations)'
  },
  {
    id: 'shankhapushpi',
    sanskritName: 'Shankhapushpi',
    hindiName: 'शंखपुष्पी',
    commonName: 'Shankhapushpi',
    botanicalName: 'Convolvulus pluricaulis Choisy',
    family: 'Convolvulaceae',
    plantPartsUsed: ['Whole plant'],
    pharmacopoeiaRef: 'Ayurvedic Pharmacopoeia of India (API) Part I, Vol. II, Page 147',
    classicalYogas: ['Brahmi Ghrita', 'Shankhapushpi Syrup', 'Saraswatarishta'],
    indications: ['Medhya (Nootropic)', 'Apasmara (Epilepsy)', 'Unmada (Psychosis)'],
    traditionalKnowledgeSummary: 'Highly regarded in Charaka Samhita as the best Medhya Rasayana (cognitive enhancer).',
    tkdlReference: 'TKDL Identifier: CS-256 (Convolvulus pluricaulis cognitive formulations)'
  },
  {
    id: 'sariva',
    sanskritName: 'Sariva',
    hindiName: 'अनंतमूल',
    commonName: 'Indian Sarsaparilla',
    botanicalName: 'Hemidesmus indicus (L.) R. Br.',
    family: 'Apocynaceae',
    plantPartsUsed: ['Root'],
    pharmacopoeiaRef: 'Ayurvedic Pharmacopoeia of India (API) Part I, Vol. I, Page 107',
    classicalYogas: ['Sarivadyasava', 'Maha Manjisthadi Kwatha'],
    indications: ['Raktashodhaka (Blood purifier)', 'Daha (Burning sensation)', 'Kustha (Skin disorders)'],
    traditionalKnowledgeSummary: 'Documented in Sushruta Samhita for treating skin diseases and blood purification.',
    tkdlReference: 'TKDL Identifier: SS-189 (Hemidesmus indicus skin formulations)'
  },
  {
    id: 'bakuchi',
    sanskritName: 'Bakuchi',
    hindiName: 'बाकुची',
    commonName: 'Psoralea',
    botanicalName: 'Psoralea corylifolia L.',
    family: 'Fabaceae',
    plantPartsUsed: ['Seed'],
    pharmacopoeiaRef: 'Ayurvedic Pharmacopoeia of India (API) Part I, Vol. I, Page 21',
    classicalYogas: ['Bakuchi Churna', 'Somaraji Taila'],
    indications: ['Shvitra (Leucoderma/Vitiligo)', 'Kustha (Skin diseases)'],
    traditionalKnowledgeSummary: 'Bhavaprakasha specifies it as the primary herb for Shvitra (vitiligo).',
    tkdlReference: 'TKDL Identifier: BPN-234 (Psoralea corylifolia vitiligo formulations)'
  },
  {
    id: 'devdaru',
    sanskritName: 'Devadaru',
    hindiName: 'देवदार',
    commonName: 'Deodar Cedar',
    botanicalName: 'Cedrus deodara (Roxb.) G.Don',
    family: 'Pinaceae',
    plantPartsUsed: ['Heartwood'],
    pharmacopoeiaRef: 'Ayurvedic Pharmacopoeia of India (API) Part I, Vol. IV, Page 31',
    classicalYogas: ['Devadarvyadi Kwatha', 'Chandraprabha Vati'],
    indications: ['Vatahara (Neurological)', 'Peenasa (Rhinitis)', 'Kasa (Cough)'],
    traditionalKnowledgeSummary: 'Charaka Samhita classifies it under Stanyashodhana (breast milk purifying).',
    tkdlReference: 'TKDL Identifier: CS-432 (Cedrus deodara neurological formulations)'
  },
  {
    id: 'agnimantha',
    sanskritName: 'Agnimantha',
    hindiName: 'अग्निमंथ',
    commonName: 'Agnimantha',
    botanicalName: 'Premna serratifolia L.',
    family: 'Lamiaceae',
    plantPartsUsed: ['Root', 'Bark'],
    pharmacopoeiaRef: 'Ayurvedic Pharmacopoeia of India (API) Part I, Vol. III, Page 3',
    classicalYogas: ['Dashamularishta', 'Narayan Taila'],
    indications: ['Shothahara (Anti-inflammatory)', 'Vatahara'],
    traditionalKnowledgeSummary: 'One of the roots in Dashamula, widely used in Charaka and Sushruta for Vata disorders.',
    tkdlReference: 'TKDL Identifier: CS-Dash-01 (Premna serratifolia formulations)'
  },
  {
    id: 'prishniparni',
    sanskritName: 'Prishniparni',
    hindiName: 'पृश्निपर्णी',
    commonName: 'Prishniparni',
    botanicalName: 'Uraria picta (Jacq.) DC.',
    family: 'Fabaceae',
    plantPartsUsed: ['Root', 'Whole plant'],
    pharmacopoeiaRef: 'Ayurvedic Pharmacopoeia of India (API) Part I, Vol. II, Page 135',
    classicalYogas: ['Dashamularishta', 'Chyawanprash'],
    indications: ['Tridoshahara', 'Angamarda (Body ache)', 'Atisara (Diarrhea)'],
    traditionalKnowledgeSummary: 'A crucial ingredient of Laghu Panchamula in Charaka Samhita.',
    tkdlReference: 'TKDL Identifier: CS-Dash-02 (Uraria picta formulations)'
  },
  {
    id: 'shalaparni',
    sanskritName: 'Shalaparni',
    hindiName: 'शालपर्णी',
    commonName: 'Shalaparni',
    botanicalName: 'Desmodium gangeticum (L.) DC.',
    family: 'Fabaceae',
    plantPartsUsed: ['Root', 'Whole plant'],
    pharmacopoeiaRef: 'Ayurvedic Pharmacopoeia of India (API) Part I, Vol. I, Page 104',
    classicalYogas: ['Dashamularishta', 'Chyawanprash'],
    indications: ['Jwara (Fever)', 'Kasa', 'Balya'],
    traditionalKnowledgeSummary: 'Part of the Laghu Panchamula, highly valued for fevers and as a cardiac tonic.',
    tkdlReference: 'TKDL Identifier: CS-Dash-03 (Desmodium gangeticum formulations)'
  },
  {
    id: 'kantakari',
    sanskritName: 'Kantakari',
    hindiName: 'कंटकारी',
    commonName: 'Yellow-berried Nightshade',
    botanicalName: 'Solanum surattense Burm.f.',
    family: 'Solanaceae',
    plantPartsUsed: ['Whole plant', 'Root'],
    pharmacopoeiaRef: 'Ayurvedic Pharmacopoeia of India (API) Part I, Vol. I, Page 59',
    classicalYogas: ['Dashamularishta', 'Kantakari Avaleha', 'Vyaghritaila'],
    indications: ['Kasa', 'Shvasa', 'Peenasa (Rhinitis)'],
    traditionalKnowledgeSummary: 'Mentioned in Charaka Samhita as the best herb for respiratory conditions (Kasa-Shvasa).',
    tkdlReference: 'TKDL Identifier: CS-Dash-04 (Solanum surattense respiratory formulations)'
  },
  {
    id: 'brihati',
    sanskritName: 'Brihati',
    hindiName: 'बड़ी कटेरी',
    commonName: 'Indian Nightshade',
    botanicalName: 'Solanum indicum L.',
    family: 'Solanaceae',
    plantPartsUsed: ['Root', 'Fruit'],
    pharmacopoeiaRef: 'Ayurvedic Pharmacopoeia of India (API) Part I, Vol. II, Page 27',
    classicalYogas: ['Dashamularishta', 'Chyawanprash'],
    indications: ['Kasa', 'Shvasa', 'Aruchi (Anorexia)'],
    traditionalKnowledgeSummary: 'Part of Dashamula, often used together with Kantakari for pulmonary support.',
    tkdlReference: 'TKDL Identifier: CS-Dash-05 (Solanum indicum formulations)'
  },
  {
    id: 'bilwa',
    sanskritName: 'Bilva',
    hindiName: 'बेल',
    commonName: 'Bael',
    botanicalName: 'Aegle marmelos (L.) Correa',
    family: 'Rutaceae',
    plantPartsUsed: ['Fruit', 'Root bark', 'Leaves'],
    pharmacopoeiaRef: 'Ayurvedic Pharmacopoeia of India (API) Part I, Vol. I, Page 27',
    classicalYogas: ['Bilvadi Churna', 'Dashamularishta', 'Gangadhara Churna'],
    indications: ['Grahani (IBS)', 'Atisara (Diarrhea)', 'Shothahara'],
    traditionalKnowledgeSummary: 'Unripe fruit widely praised in Charaka Samhita for gastrointestinal motility disorders (Grahani).',
    tkdlReference: 'TKDL Identifier: CS-Dash-06 (Aegle marmelos gastrointestinal formulations)'
  },
  {
    id: 'gambhari',
    sanskritName: 'Gambhari',
    hindiName: 'गंभारी',
    commonName: 'Beechwood',
    botanicalName: 'Gmelina arborea Roxb.',
    family: 'Lamiaceae',
    plantPartsUsed: ['Root bark', 'Fruit'],
    pharmacopoeiaRef: 'Ayurvedic Pharmacopoeia of India (API) Part I, Vol. I, Page 37',
    classicalYogas: ['Dashamularishta', 'Shriparni Taila'],
    indications: ['Daha (Burning sensation)', 'Trishna (Thirst)', 'Balya'],
    traditionalKnowledgeSummary: 'A Brihat Panchamula root; its fruit is uniquely described as a Medhya and Rasayana.',
    tkdlReference: 'TKDL Identifier: CS-Dash-07 (Gmelina arborea formulations)'
  },
  {
    id: 'patala',
    sanskritName: 'Patala',
    hindiName: 'पाटल',
    commonName: 'Rose Flower Fragrant',
    botanicalName: 'Stereospermum suaveolens (Roxb.) DC.',
    family: 'Bignoniaceae',
    plantPartsUsed: ['Root bark', 'Flower'],
    pharmacopoeiaRef: 'Ayurvedic Pharmacopoeia of India (API) Part I, Vol. III, Page 147',
    classicalYogas: ['Dashamularishta', 'Patala Taila'],
    indications: ['Shothahara', 'Raktapitta', 'Hikka (Hiccup)'],
    traditionalKnowledgeSummary: 'Part of Dashamula, utilized in Charaka Samhita for calming Pitta and Vata.',
    tkdlReference: 'TKDL Identifier: CS-Dash-08 (Stereospermum suaveolens formulations)'
  },
  {
    id: 'shyonaka',
    sanskritName: 'Shyonaka',
    hindiName: 'श्योनाक',
    commonName: 'Indian Oroxylum',
    botanicalName: 'Oroxylum indicum (L.) Kurz',
    family: 'Bignoniaceae',
    plantPartsUsed: ['Root bark'],
    pharmacopoeiaRef: 'Ayurvedic Pharmacopoeia of India (API) Part I, Vol. I, Page 109',
    classicalYogas: ['Dashamularishta', 'Brahma Rasayana'],
    indications: ['Amavata', 'Atisara', 'Shothahara'],
    traditionalKnowledgeSummary: 'Root bark of this Dashamula plant is valued in treating rheumatoid and inflammatory conditions.',
    tkdlReference: 'TKDL Identifier: CS-Dash-09 (Oroxylum indicum formulations)'
  },
  {
    id: 'eranda',
    sanskritName: 'Eranda',
    hindiName: 'अरंडी',
    commonName: 'Castor',
    botanicalName: 'Ricinus communis L.',
    family: 'Euphorbiaceae',
    plantPartsUsed: ['Root', 'Seed oil', 'Leaves'],
    pharmacopoeiaRef: 'Ayurvedic Pharmacopoeia of India (API) Part I, Vol. I, Page 34',
    classicalYogas: ['Eranda Paka', 'Gandharvahastadi Kashayam'],
    indications: ['Amavata', 'Vatavyadhi', 'Vibandha (Constipation)'],
    traditionalKnowledgeSummary: 'Described by Charaka as the single best herb for Vata disorders.',
    tkdlReference: 'TKDL Identifier: CS-409 (Ricinus communis formulations)'
  },
  {
    id: 'trivrit',
    sanskritName: 'Trivrit',
    hindiName: 'निशोथ',
    commonName: 'Indian Jalap',
    botanicalName: 'Operculina turpethum (L.) Silva Manso',
    family: 'Convolvulaceae',
    plantPartsUsed: ['Root'],
    pharmacopoeiaRef: 'Ayurvedic Pharmacopoeia of India (API) Part I, Vol. III, Page 211',
    classicalYogas: ['Avipattikar Churna', 'Trivrit Lehyam'],
    indications: ['Virechana (Purgation)', 'Udavarta', 'Kamala'],
    traditionalKnowledgeSummary: 'The foremost drug for therapeutic purgation (Virechana) in Charaka Samhita.',
    tkdlReference: 'TKDL Identifier: CS-509 (Operculina turpethum laxative preparations)'
  },
  {
    id: 'tagara',
    sanskritName: 'Tagara',
    hindiName: 'तगर',
    commonName: 'Indian Valerian',
    botanicalName: 'Valeriana wallichii DC.',
    family: 'Caprifoliaceae',
    plantPartsUsed: ['Rhizome', 'Root'],
    pharmacopoeiaRef: 'Ayurvedic Pharmacopoeia of India (API) Part I, Vol. I, Page 108',
    classicalYogas: ['Jatamansiadi Churna', 'Mahanarayana Taila'],
    indications: ['Nidranasha (Insomnia)', 'Apasmara', 'Vishaghna'],
    traditionalKnowledgeSummary: 'Renowned for its sedative and nervine properties in Sushruta Samhita.',
    tkdlReference: 'TKDL Identifier: SS-210 (Valeriana wallichii formulations)'
  },
  {
    id: 'kesar',
    sanskritName: 'Kumkuma',
    hindiName: 'केसर',
    commonName: 'Saffron',
    botanicalName: 'Crocus sativus L.',
    family: 'Iridaceae',
    plantPartsUsed: ['Style and Stigma'],
    pharmacopoeiaRef: 'Ayurvedic Pharmacopoeia of India (API) Part I, Vol. IV, Page 54',
    classicalYogas: ['Kumkumadi Taila', 'Pushyanuga Churna'],
    indications: ['Varnya (Complexion enhancing)', 'Vrushya', 'Drishtida (Vision improving)'],
    traditionalKnowledgeSummary: 'Most precious spice in Ayurveda, highly valued for Varnya (skin radiance) and female reproductive health.',
    tkdlReference: 'TKDL Identifier: AH-112 (Crocus sativus formulations)'
  },
  {
    id: 'ativisha',
    sanskritName: 'Ativisha',
    hindiName: 'अतीस',
    commonName: 'Indian Atees',
    botanicalName: 'Aconitum heterophyllum Wall. ex Royle',
    family: 'Ranunculaceae',
    plantPartsUsed: ['Root tuber'],
    pharmacopoeiaRef: 'Ayurvedic Pharmacopoeia of India (API) Part I, Vol. I, Page 14',
    classicalYogas: ['Balachaturbhadra Churna', 'Pushyanuga Churna'],
    indications: ['Balaroga (Pediatric disorders)', 'Atisara', 'Jwara'],
    traditionalKnowledgeSummary: 'A non-toxic Aconite species used specifically in pediatrics (Balaroga) as per Vagbhata.',
    tkdlReference: 'TKDL Identifier: AH-119 (Aconitum heterophyllum formulations)'
  },
  {
    id: 'dhattura',
    sanskritName: 'Dhattura',
    hindiName: 'धतूरा',
    commonName: 'Thorn Apple',
    botanicalName: 'Datura metel L.',
    family: 'Solanaceae',
    plantPartsUsed: ['Seed', 'Leaves'],
    pharmacopoeiaRef: 'Ayurvedic Pharmacopoeia of India (API) Part I, Vol. III, Page 43',
    classicalYogas: ['Dhattura Taila', 'Kanakasava'],
    indications: ['Shvasa (Asthma)', 'Sandhivata (Joint pain)'],
    traditionalKnowledgeSummary: 'A potent Upavisha (toxic plant) used in minute, purified quantities for bronchial spasms.',
    tkdlReference: 'TKDL Identifier: BR-154 (Datura metel preparations)'
  },
  {
    id: 'apamarga',
    sanskritName: 'Apamarga',
    hindiName: 'अपामार्ग / चिरचिटा',
    commonName: 'Prickly Chaff Flower',
    botanicalName: 'Achyranthes aspera L.',
    family: 'Amaranthaceae',
    plantPartsUsed: ['Whole plant', 'Seed'],
    pharmacopoeiaRef: 'Ayurvedic Pharmacopoeia of India (API) Part I, Vol. II, Page 10',
    classicalYogas: ['Apamarga Kshara', 'Apamargadi Taila'],
    indications: ['Karnaroga (Ear diseases)', 'Krimighna', 'Arsha (Hemorrhoids)'],
    traditionalKnowledgeSummary: 'Its alkaline ash (Kshara) is heavily used in Shalya Tantra (surgery) and for making Ksharasutra.',
    tkdlReference: 'TKDL Identifier: SS-105 (Achyranthes aspera surgical/topical preparations)'
  },
  {
    id: 'lajjalu',
    sanskritName: 'Lajjalu',
    hindiName: 'छुईमुई',
    commonName: 'Sensitive Plant',
    botanicalName: 'Mimosa pudica L.',
    family: 'Fabaceae',
    plantPartsUsed: ['Whole plant'],
    pharmacopoeiaRef: 'Ayurvedic Pharmacopoeia of India (API) Part I, Vol. II, Page 98',
    classicalYogas: ['Samangadi Churna', 'Kutajarishta (as adjunct)'],
    indications: ['Raktapitta', 'Atisara', 'Vranaropana'],
    traditionalKnowledgeSummary: 'Used extensively for bleeding disorders and wound healing in classical texts.',
    tkdlReference: 'TKDL Identifier: CS-412 (Mimosa pudica hemostatic formulations)'
  },
  {
    id: 'palasha',
    sanskritName: 'Palasha',
    hindiName: 'पलाश / ढाक',
    commonName: 'Flame of the Forest',
    botanicalName: 'Butea monosperma (Lam.) Taub.',
    family: 'Fabaceae',
    plantPartsUsed: ['Seed', 'Bark', 'Flower', 'Gum'],
    pharmacopoeiaRef: 'Ayurvedic Pharmacopoeia of India (API) Part I, Vol. II, Page 125',
    classicalYogas: ['Palashabija Churna', 'Krimikuthar Ras'],
    indications: ['Krimighna', 'Prameha', 'Raktapitta'],
    traditionalKnowledgeSummary: 'Seeds are one of the best anthelmintics (Krimighna) as described in Sushruta Samhita.',
    tkdlReference: 'TKDL Identifier: SS-233 (Butea monosperma anthelmintic preparations)'
  },
  {
    id: 'ashoka',
    sanskritName: 'Ashoka',
    hindiName: 'अशोक',
    commonName: 'Ashoka Tree',
    botanicalName: 'Saraca asoca (Roxb.) de Wilde',
    family: 'Fabaceae',
    plantPartsUsed: ['Stem bark'],
    pharmacopoeiaRef: 'Ayurvedic Pharmacopoeia of India (API) Part I, Vol. I, Page 17',
    classicalYogas: ['Ashokarishta', 'Ashoka Ghrita'],
    indications: ['Pradara (Leucorrhoea/Menorrhagia)', 'Garbhashaya-vikara (Uterine disorders)'],
    traditionalKnowledgeSummary: 'The foremost drug for gynecological conditions in Ayurveda, regulating menstrual flow and easing cramps.',
    tkdlReference: 'TKDL Identifier: BPN-310 (Saraca asoca gynecological formulations)'
  },
  {
    id: 'lodhra',
    sanskritName: 'Lodhra',
    hindiName: 'लोध्र',
    commonName: 'Symplocos Bark',
    botanicalName: 'Symplocos racemosa Roxb.',
    family: 'Symplocaceae',
    plantPartsUsed: ['Stem bark'],
    pharmacopoeiaRef: 'Ayurvedic Pharmacopoeia of India (API) Part I, Vol. I, Page 82',
    classicalYogas: ['Lodhrasava', 'Pushyanuga Churna'],
    indications: ['Raktapitta', 'Pradara', 'Shothahara', 'Mukharoga'],
    traditionalKnowledgeSummary: 'Often paired with Ashoka for treating bleeding disorders and oral/gum diseases.',
    tkdlReference: 'TKDL Identifier: CS-452 (Symplocos racemosa formulations)'
  },
  {
    id: 'nagkesar',
    sanskritName: 'Nagakeshara',
    hindiName: 'नागकेसर',
    commonName: 'Cobras Saffron / Ironwood',
    botanicalName: 'Mesua ferrea L.',
    family: 'Calophyllaceae',
    plantPartsUsed: ['Stamens'],
    pharmacopoeiaRef: 'Ayurvedic Pharmacopoeia of India (API) Part I, Vol. II, Page 112',
    classicalYogas: ['Chyawanprash', 'Pushyanuga Churna', 'Kanchanar Guggulu'],
    indications: ['Raktarsha (Bleeding piles)', 'Raktapitta', 'Trishna'],
    traditionalKnowledgeSummary: 'Highly effective hemostatic used widely in hemorrhoid treatments (Raktarsha).',
    tkdlReference: 'TKDL Identifier: BPN-192 (Mesua ferrea hemostatic formulations)'
  },
  {
    id: 'rasna',
    sanskritName: 'Rasna',
    hindiName: 'रास्ना',
    commonName: 'Indian Camphorweed',
    botanicalName: 'Pluchea lanceolata (DC.) C.B.Clarke',
    family: 'Asteraceae',
    plantPartsUsed: ['Leaf'],
    pharmacopoeiaRef: 'Ayurvedic Pharmacopoeia of India (API) Part I, Vol. III, Page 164',
    classicalYogas: ['Maha Rasnadi Kwatha', 'Rasna Saptaka Kwatha'],
    indications: ['Amavata', 'Sandhivata', 'Vatavyadhi'],
    traditionalKnowledgeSummary: 'Charaka specifies Rasna as the drug of choice for all Vata disorders (Vataharanam shreshtha).',
    tkdlReference: 'TKDL Identifier: CS-465 (Pluchea lanceolata rheumatological formulations)'
  },
  {
    id: 'dadima',
    sanskritName: 'Dadima',
    hindiName: 'अनार',
    commonName: 'Pomegranate',
    botanicalName: 'Punica granatum L.',
    family: 'Lythraceae',
    plantPartsUsed: ['Fruit rind', 'Seeds', 'Root bark'],
    pharmacopoeiaRef: 'Ayurvedic Pharmacopoeia of India (API) Part I, Vol. IV, Page 17',
    classicalYogas: ['Dadimadi Ghrita', 'Bhaskar Lavana Churna'],
    indications: ['Aruchi', 'Trishna', 'Raktapitta', 'Amlapitta'],
    traditionalKnowledgeSummary: 'Considered extremely wholesome (Pathya); balances Pitta and Vata.',
    tkdlReference: 'TKDL Identifier: CS-388 (Punica granatum digestive formulations)'
  },
  {
    id: 'dronapushpi',
    sanskritName: 'Dronapushpi',
    hindiName: 'गोमा',
    commonName: 'Leucas',
    botanicalName: 'Leucas cephalotes (Roth) Spreng.',
    family: 'Lamiaceae',
    plantPartsUsed: ['Whole plant'],
    pharmacopoeiaRef: 'Ayurvedic Pharmacopoeia of India (API) Part I, Vol. II, Page 39',
    classicalYogas: ['Plihari Vati', 'Dronapushpi Swarasa'],
    indications: ['Vishama Jwara (Malaria/Intermittent fever)', 'Kamala', 'Krimighna'],
    traditionalKnowledgeSummary: 'A potent remedy for intermittent fevers and liver-spleen disorders.',
    tkdlReference: 'TKDL Identifier: BPN-299 (Leucas cephalotes fever formulations)'
  },
  {
    id: 'durva',
    sanskritName: 'Durva',
    hindiName: 'दूब',
    commonName: 'Bermuda Grass',
    botanicalName: 'Cynodon dactylon (L.) Pers.',
    family: 'Poaceae',
    plantPartsUsed: ['Whole plant'],
    pharmacopoeiaRef: 'Ayurvedic Pharmacopoeia of India (API) Part I, Vol. III, Page 47',
    classicalYogas: ['Durvadi Ghrita', 'Durvadi Taila'],
    indications: ['Raktapitta', 'Daha', 'Visarpa (Erysipelas)', 'Vranaropana'],
    traditionalKnowledgeSummary: 'Excellent for bleeding disorders; used topically and internally.',
    tkdlReference: 'TKDL Identifier: CS-481 (Cynodon dactylon skin/bleeding formulations)'
  },
  {
    id: 'ela',
    sanskritName: 'Ela',
    hindiName: 'इलायची',
    commonName: 'Cardamom',
    botanicalName: 'Elettaria cardamomum (L.) Maton',
    family: 'Zingiberaceae',
    plantPartsUsed: ['Seeds'],
    pharmacopoeiaRef: 'Ayurvedic Pharmacopoeia of India (API) Part I, Vol. I, Page 102',
    classicalYogas: ['Eladi Vati', 'Sitopaladi Churna', 'Chyawanprash'],
    indications: ['Kasa', 'Shvasa', 'Aruchi', 'Mutrakrichchhra'],
    traditionalKnowledgeSummary: 'A primary flavoring and therapeutic agent in Ayurveda for respiratory and digestive ailments.',
    tkdlReference: 'TKDL Identifier: CS-203 (Elettaria cardamomum formulations)'
  },
  {
    id: 'lavanga',
    sanskritName: 'Lavanga',
    hindiName: 'लौंग',
    commonName: 'Clove',
    botanicalName: 'Syzygium aromaticum (L.) Merr. & L.M.Perry',
    family: 'Myrtaceae',
    plantPartsUsed: ['Flower bud'],
    pharmacopoeiaRef: 'Ayurvedic Pharmacopoeia of India (API) Part I, Vol. I, Page 80',
    classicalYogas: ['Lavangadi Vati', 'Khadiradi Vati'],
    indications: ['Kasa', 'Shvasa', 'Dantaroga (Dental issues)', 'Aruchi'],
    traditionalKnowledgeSummary: 'Used widely in oral health and respiratory syrups.',
    tkdlReference: 'TKDL Identifier: BR-412 (Syzygium aromaticum formulations)'
  },
  {
    id: 'twak',
    sanskritName: 'Twak',
    hindiName: 'दालचीनी',
    commonName: 'Cinnamon',
    botanicalName: 'Cinnamomum zeylanicum Blume',
    family: 'Lauraceae',
    plantPartsUsed: ['Inner stem bark'],
    pharmacopoeiaRef: 'Ayurvedic Pharmacopoeia of India (API) Part I, Vol. I, Page 115',
    classicalYogas: ['Sitopaladi Churna', 'Talisadi Churna'],
    indications: ['Aruchi', 'Prameha', 'Peenasa', 'Kasa'],
    traditionalKnowledgeSummary: 'A key spice in Trijata (with Ela and Patra) used to enhance digestion and metabolism.',
    tkdlReference: 'TKDL Identifier: CS-289 (Cinnamomum zeylanicum formulations)'
  },
  {
    id: 'jatiphala',
    sanskritName: 'Jatiphala',
    hindiName: 'जायफल',
    commonName: 'Nutmeg',
    botanicalName: 'Myristica fragrans Houtt.',
    family: 'Myristicaceae',
    plantPartsUsed: ['Seed', 'Mace (Jatipatri)'],
    pharmacopoeiaRef: 'Ayurvedic Pharmacopoeia of India (API) Part I, Vol. I, Page 57',
    classicalYogas: ['Jatphaladi Churna', 'Lavangadi Vati'],
    indications: ['Atisara', 'Grahani', 'Shukraskhalana (Premature ejaculation)'],
    traditionalKnowledgeSummary: 'Used for gastrointestinal distress and as a sedative/aphrodisiac.',
    tkdlReference: 'TKDL Identifier: SS-315 (Myristica fragrans formulations)'
  },
  {
    id: 'dhanyaka',
    sanskritName: 'Dhanyaka',
    hindiName: 'धनिया',
    commonName: 'Coriander',
    botanicalName: 'Coriandrum sativum L.',
    family: 'Apiaceae',
    plantPartsUsed: ['Fruit/Seed', 'Leaf'],
    pharmacopoeiaRef: 'Ayurvedic Pharmacopoeia of India (API) Part I, Vol. I, Page 35',
    classicalYogas: ['Dhanyakadi Hima', 'Abhayarishta'],
    indications: ['Daha (Burning sensation)', 'Trishna', 'Amlapitta (Hyperacidity)'],
    traditionalKnowledgeSummary: 'Known for its cooling effect (Sheeta Virya) despite being a digestive (Deepana-Pachana).',
    tkdlReference: 'TKDL Identifier: CS-340 (Coriandrum sativum formulations)'
  },
  {
    id: 'jeera',
    sanskritName: 'Jeeraka',
    hindiName: 'जीरा',
    commonName: 'Cumin',
    botanicalName: 'Cuminum cyminum L.',
    family: 'Apiaceae',
    plantPartsUsed: ['Fruit'],
    pharmacopoeiaRef: 'Ayurvedic Pharmacopoeia of India (API) Part I, Vol. I, Page 58',
    classicalYogas: ['Hingwashtak Churna', 'Jeerakarishta'],
    indications: ['Agnimandya', 'Atisara', 'Sutikaroga (Post-natal care)'],
    traditionalKnowledgeSummary: 'Excellent Deepana (appetizer) widely used in post-partum recovery.',
    tkdlReference: 'TKDL Identifier: CS-344 (Cuminum cyminum formulations)'
  },
  {
    id: 'ajwain',
    sanskritName: 'Yavani',
    hindiName: 'अजवायन',
    commonName: 'Bishop\'s Weed / Ajwain',
    botanicalName: 'Trachyspermum ammi (L.) Sprague',
    family: 'Apiaceae',
    plantPartsUsed: ['Fruit'],
    pharmacopoeiaRef: 'Ayurvedic Pharmacopoeia of India (API) Part I, Vol. I, Page 128',
    classicalYogas: ['Yavani Khanda', 'Hingwashtak Churna'],
    indications: ['Shula (Colic)', 'Udara (Ascites/Abdominal disorders)', 'Krimi'],
    traditionalKnowledgeSummary: 'Contains thymol, heavily used for antispasmodic and carminative effects.',
    tkdlReference: 'TKDL Identifier: BPN-218 (Trachyspermum ammi digestive formulations)'
  },
  {
    id: 'methika',
    sanskritName: 'Methika',
    hindiName: 'मेथी',
    commonName: 'Fenugreek',
    botanicalName: 'Trigonella foenum-graecum L.',
    family: 'Fabaceae',
    plantPartsUsed: ['Seed', 'Leaf'],
    pharmacopoeiaRef: 'Ayurvedic Pharmacopoeia of India (API) Part I, Vol. II, Page 108',
    classicalYogas: ['Methi Modaka'],
    indications: ['Prameha (Diabetes)', 'Vatavyadhi', 'Agnimandya'],
    traditionalKnowledgeSummary: 'Documented in later Nighantus; highly popular for metabolic control (Prameha).',
    tkdlReference: 'TKDL Identifier: BPN-405 (Trigonella foenum-graecum metabolic formulations)'
  },
  {
    id: 'vasa',
    sanskritName: 'Vasa',
    hindiName: 'अडूसा',
    commonName: 'Malabar Nut',
    botanicalName: 'Adhatoda vasica Nees',
    family: 'Acanthaceae',
    plantPartsUsed: ['Leaf', 'Root'],
    pharmacopoeiaRef: 'Ayurvedic Pharmacopoeia of India (API) Part I, Vol. I, Page 122',
    classicalYogas: ['Vasavaleha', 'Panchatikta Ghrita', 'Vasarishta'],
    indications: ['Kasa', 'Shvasa', 'Raktapitta (Bleeding disorders)'],
    traditionalKnowledgeSummary: 'Charaka emphasizes Vasa for respiratory conditions and managing internal bleeding (Raktapitta). Contains vasicine.',
    tkdlReference: 'TKDL Identifier: CS-489 (Adhatoda vasica respiratory/hemostatic formulations)'
  }
];

export const CLASSICAL_YOGAS: ClassicalYoga[] = [
  {
    id: 'yogaraja-guggulu',
    name: 'Yogaraja Guggulu',
    sanskritName: 'योगराज गुग्गुलु',
    authoritativeText: 'Bhaishajya Ratnavali (First Schedule to D&C Act 1940)',
    chapterSection: 'Amavata Rogadhikara, Shlokas 90-95',
    primaryIngredients: ['Guggulu (purified)', 'Chitraka', 'Pippalimula', 'Yavani', 'Jeeraka', 'Vidanga', 'Ajamoda', 'Haritaki', 'Bibhitaki', 'Amalaki', 'Sunthi', 'Maricha', 'Pippali'],
    dosageForm: 'Vati / Gutika (Tablet)',
    classicalIndication: 'Amavata (Rheumatoid arthritis), Sandhivata (Osteoarthritis), Vatavyadhi (Neuro-muscular disorders)',
    isClassicalGeneric: true
  },
  {
    id: 'triphala-churna',
    name: 'Triphala Churna',
    sanskritName: 'त्रिफला चूर्ण',
    authoritativeText: 'Charaka Samhita & Sharangadhara Samhita (First Schedule)',
    chapterSection: 'Charaka Samhita Chikitsasthana 1:3; Sharangadhara Madhyama Khanda 6',
    primaryIngredients: ['Amalaki (Phyllanthus emblica)', 'Haritaki (Terminalia chebula)', 'Bibhitaki (Terminalia bellirica)'],
    dosageForm: 'Churna (Powder)',
    classicalIndication: 'Chakshushya (Vision enhancer), Deepana-Pachana (Digestive), Pramehahara, Rasayana',
    isClassicalGeneric: true
  },
  {
    id: 'mahanarayana-taila',
    name: 'Mahanarayana Taila',
    sanskritName: 'महानारायण तैल',
    authoritativeText: 'Bhaishajya Ratnavali (First Schedule)',
    chapterSection: 'Vatavyadhi Rogadhikara, Shlokas 140-155',
    primaryIngredients: ['Bilva', 'Ashwagandha', 'Brihati', 'Kantakari', 'Shatavari', 'Gokshura', 'Tila Taila'],
    dosageForm: 'Taila (Medicated Oil)',
    classicalIndication: 'Vatavyadhi (Joint stiffness, paralysis, muscular atrophy, hemiplegia)',
    isClassicalGeneric: true
  },
  {
    id: 'ashwagandharishta',
    name: 'Ashwagandharishta',
    sanskritName: 'अश्वगन्धारिष्ट',
    authoritativeText: 'Bhaishajya Ratnavali (First Schedule)',
    chapterSection: 'Murcha Rogadhikara, Shlokas 13-17',
    primaryIngredients: ['Ashwagandha', 'Musali', 'Manjistha', 'Haridra', 'Daruharidra', 'Yashtimadhu', 'Rasna', 'Vidari', 'Dhataki'],
    dosageForm: 'Asava / Arishta (Fermented Liquid)',
    classicalIndication: 'Murcha, Apasmara, Karshya (Emaciation), Vata imbalances, Stress exhaustion',
    isClassicalGeneric: true
  },
  {
    id: 'chyawanprash',
    name: 'Chyawanprash Rasayana',
    sanskritName: 'च्यवनप्राश रसायन',
    authoritativeText: 'Charaka Samhita (First Schedule)',
    chapterSection: 'Chikitsasthana Chapter 1, Pada 1, Shlokas 62-74',
    primaryIngredients: ['Amalaki', 'Dashamula', 'Bala', 'Musta', 'Punarvana', 'Guduchi', 'Pippali', 'Draksha', 'Ghrita', 'Taila', 'Madhu'],
    dosageForm: 'Avaleha / Lehya (Herbal Jam)',
    classicalIndication: 'Rasayana (Vitality & Longevity), Kasa (Cough), Shvasa (Dyspnea), Kshaya (Debility)',
    isClassicalGeneric: true
  },
  {
    id: 'chandraprabha-vati',
    name: 'Chandraprabha Vati',
    sanskritName: 'चन्द्रप्रभा वटी',
    authoritativeText: 'Sharangadhara Samhita (First Schedule)',
    chapterSection: 'Madhyama Khanda Chapter 7 Shlokas 1-12',
    primaryIngredients: ['Chandraprabha (Camphor)', 'Vacha', 'Musta', 'Bhunimba', 'Guduchi', 'Daruharidra', 'Haridra', 'Triphala', 'Trikatu', 'Guggulu', 'Shilajatu', 'Loha Bhasma'],
    dosageForm: 'Vati (Tablet)',
    classicalIndication: 'Prameha (Diabetes/Urinary), Mutrakrichchhra (Dysuria), Pandu (Anemia), Medoroga',
    isClassicalGeneric: true
  },
  {
    id: 'kaishore-guggulu',
    name: 'Kaishore Guggulu',
    sanskritName: 'कैशोर गुग्गुलु',
    authoritativeText: 'Sharangadhara Samhita (First Schedule)',
    chapterSection: 'Madhyama Khanda Chapter 7',
    primaryIngredients: ['Guggulu (purified)', 'Triphala', 'Guduchi', 'Trikatu', 'Vidanga', 'Danti Mula', 'Trivrit'],
    dosageForm: 'Vati (Tablet)',
    classicalIndication: 'Vatarakta (Gout), Kustha (Skin disorders), Vrana (Ulcers), Nadivrana',
    isClassicalGeneric: true
  },
  {
    id: 'dashamularishta',
    name: 'Dashamularishta',
    sanskritName: 'दशमूलारिष्ट',
    authoritativeText: 'Bhaishajya Ratnavali (First Schedule)',
    chapterSection: 'Stree Rogadhikara',
    primaryIngredients: ['Dashamula group (Bilva, Agnimantha, Shyonaka, Patala, Gambhari, Brihati, Kantakari, Gokshura, Shalaparni, Prishniparni)', 'Dhataki', 'Jaggery'],
    dosageForm: 'Arishta (Fermented Liquid)',
    classicalIndication: 'Sutika Roga (Postpartum), Jwara, Shvasa, Balya',
    isClassicalGeneric: true
  },
  {
    id: 'draksharishta',
    name: 'Draksharishta',
    sanskritName: 'द्राक्षारिष्ट',
    authoritativeText: 'Bhaishajya Ratnavali (First Schedule)',
    chapterSection: 'Raktapitta Rogadhikara',
    primaryIngredients: ['Draksha (Vitis vinifera)', 'Madhuka', 'Dhataki', 'Pippali', 'Nagakeshara', 'Twak', 'Ela', 'Jaggery'],
    dosageForm: 'Arishta (Fermented Liquid)',
    classicalIndication: 'Raktapitta (Bleeding disorders), Pandu (Anemia), Kshaya (Debility)',
    isClassicalGeneric: true
  },
  {
    id: 'sitopaladi-churna',
    name: 'Sitopaladi Churna',
    sanskritName: 'सितोपलादि चूर्ण',
    authoritativeText: 'Sharangadhara Samhita (First Schedule)',
    chapterSection: 'Madhyama Khanda Chapter 6',
    primaryIngredients: ['Sitopala (Mishri/Rock candy)', 'Vamshalochana', 'Pippali', 'Ela', 'Twak (Cinnamon)'],
    dosageForm: 'Churna (Powder)',
    classicalIndication: 'Kasa (Cough), Shvasa (Dyspnea), Jwara, Agnimandya',
    isClassicalGeneric: true
  },
  {
    id: 'talisadi-churna',
    name: 'Talisadi Churna',
    sanskritName: 'तालीसादि चूर्ण',
    authoritativeText: 'Sharangadhara Samhita (First Schedule)',
    chapterSection: 'Madhyama Khanda Chapter 6',
    primaryIngredients: ['Talisa Patra (Abies webbiana)', 'Maricha', 'Sunthi', 'Pippali', 'Vamshalochana', 'Ela', 'Twak', 'Sitopala'],
    dosageForm: 'Churna (Powder)',
    classicalIndication: 'Kasa (Cough), Shvasa (Asthma), Pinasa (Rhinitis), Chardi (Vomiting)',
    isClassicalGeneric: true
  },
  {
    id: 'arogyavardhini-vati',
    name: 'Arogyavardhini Vati',
    sanskritName: 'आरोग्यवर्धिनी वटी',
    authoritativeText: 'Rasa Ratna Samuchchaya (First Schedule)',
    chapterSection: 'Chapter 20 Shlokas 87-92',
    primaryIngredients: ['Shuddha Parada (Purified Mercury)', 'Shuddha Gandhaka (Purified Sulfur)', 'Loha Bhasma', 'Abhraka Bhasma', 'Tamra Bhasma', 'Triphala', 'Shilajatu', 'Guggulu', 'Chitraka Mula', 'Kutaki', 'Nimba Patra'],
    dosageForm: 'Vati (Tablet)',
    classicalIndication: 'Yakrit-Pliha Vikara (Hepatosplenic disorders), Kustha, Medoroga, Kamala (Jaundice)',
    isClassicalGeneric: true
    // NOTE: Contains Shuddha Parada (purified mercury) and heavy metal Bhasmas — faces SEVERE regulatory restrictions in EU/US/Australia export markets due to heavy metal content regulations
  },
  {
    id: 'mahamanjisthadi-kwatha',
    name: 'Mahamanjisthadi Kwatha',
    sanskritName: 'महामंजिष्ठादि क्वाथ',
    authoritativeText: 'Bhaishajya Ratnavali (First Schedule)',
    chapterSection: 'Kustha Rogadhikara Shlokas 70-80',
    primaryIngredients: ['Manjistha', 'Musta', 'Kutaja', 'Guduchi', 'Nimba', 'Patola', 'Katuki', 'Haridra', 'Vacha', 'Triphala', 'Vidanga', 'Chitrak'],
    dosageForm: 'Kwatha (Decoction)',
    classicalIndication: 'Kustha (Chronic skin diseases), Raktadosha (Blood disorders), Visha (Toxicity), Shotha',
    isClassicalGeneric: true
  },
  {
    id: 'pushyanuga-churna',
    name: 'Pushyanuga Churna',
    sanskritName: 'पुष्यानुग चूर्ण',
    authoritativeText: 'Charaka Samhita (First Schedule)',
    chapterSection: 'Chikitsasthana Chapter 30 Shlokas 90-96',
    primaryIngredients: ['Pashanbheda', 'Rasanjana', 'Ativisha', 'Musta', 'Maricha', 'Lodhra', 'Katuki', 'Patha', 'Arjuna', 'Amalaki'],
    dosageForm: 'Churna (Powder)',
    classicalIndication: 'Raktapradar (Menorrhagia), Shvetapradar (Leucorrhoea), Stree-Roga (Gynecological)',
    isClassicalGeneric: true
  },
  {
    id: 'kutajarishta',
    name: 'Kutajarishta',
    sanskritName: 'कुटजारिष्ट',
    authoritativeText: 'Charaka Samhita (First Schedule)',
    chapterSection: 'Chikitsasthana Chapter 19',
    primaryIngredients: ['Kutaja twak (Holarrhena bark)', 'Dhataki', 'Mridvika (Raisins)', 'Madhuka', 'Gambhari', 'Jaggery'],
    dosageForm: 'Arishta (Fermented Liquid)',
    classicalIndication: 'Atisara (Diarrhea), Pravahika (Dysentery), Grahani (IBS), Raktaatisara',
    isClassicalGeneric: true
  },
  {
    id: 'panchatikta-ghrita-guggulu',
    name: 'Panchatikta Ghrita Guggulu',
    sanskritName: 'पंचतिक्त घृत गुग्गुलु',
    authoritativeText: 'Bhaishajya Ratnavali (First Schedule)',
    chapterSection: 'Kustha Rogadhikara Shlokas 100-108',
    primaryIngredients: ['Nimba', 'Patola', 'Kantakari', 'Guduchi', 'Vasa', 'Ghrita', 'Guggulu (purified)'],
    dosageForm: 'Ghrita-embedded Vati',
    classicalIndication: 'Kustha (Chronic dermatitis), Vatarakta (Gout), Asthi-Sandhi Vikara (Bone & joint)',
    isClassicalGeneric: true
  },
  {
    id: 'guduchi-satva',
    name: 'Guduchi Satva',
    sanskritName: 'गुडूची सत्व',
    authoritativeText: 'Bhaishajya Ratnavali / Rasa Tarangini (First Schedule)',
    chapterSection: 'Jwara Rogadhikara',
    primaryIngredients: ['Guduchi (Tinospora cordifolia) — aqueous starch extract sediment'],
    dosageForm: 'Satva (Aqueous extract concentrate)',
    classicalIndication: 'Jwara (Chronic fever), Daha (Burning sensation), Raktapitta, Prameha',
    isClassicalGeneric: true
  },
  {
    id: 'sarivadyasava',
    name: 'Sarivadyasava',
    sanskritName: 'सारिवाद्यासव',
    authoritativeText: 'Bhaishajya Ratnavali (First Schedule)',
    chapterSection: 'Raktapitta Rogadhikara',
    primaryIngredients: ['Sariva (Hemidesmus indicus)', 'Lodhra', 'Padmaka', 'Musta', 'Ushira', 'Chandana', 'Dhataki', 'Jaggery'],
    dosageForm: 'Asava (Fermented Liquid)',
    classicalIndication: 'Raktadosha (Blood purification), Kustha, Daha, Raktapitta',
    isClassicalGeneric: true
  },
  {
    id: 'lavangadi-vati',
    name: 'Lavangadi Vati',
    sanskritName: 'लवंगादि वटी',
    authoritativeText: 'Sharangadhara Samhita (First Schedule)',
    chapterSection: 'Madhyama Khanda Chapter 7',
    primaryIngredients: ['Lavanga (Syzygium aromaticum)', 'Karpura (Camphor)', 'Jatiphala (Nutmeg)', 'Ela', 'Maricha', 'Pippali', 'Twak'],
    dosageForm: 'Vati (Tablet/Lozenge)',
    classicalIndication: 'Kasa (Cough), Mukharoga (Oral disorders), Aruchi (Anorexia), Kanthya (Throat soothing)',
    isClassicalGeneric: true
  },
  {
    id: 'brahmi-ghrita',
    name: 'Brahmi Ghrita',
    sanskritName: 'ब्राह्मी घृत',
    authoritativeText: 'Charaka Samhita (First Schedule)',
    chapterSection: 'Chikitsasthana Chapter 10 Shlokas 25-30',
    primaryIngredients: ['Brahmi', 'Vacha', 'Kushtha', 'Shankhapushpi', 'Saptaparna', 'Purana Ghrita (Old clarified butter)'],
    dosageForm: 'Ghrita (Medicated Ghee)',
    classicalIndication: 'Unmada (Psychosis), Apasmara (Epilepsy), Manasa Roga (Psychiatric), Medhya',
    isClassicalGeneric: true
  },
  {
    id: 'mahalakshmivilas-ras',
    name: 'Mahalakshmivilas Ras',
    sanskritName: 'महालक्ष्मीविलास रस',
    authoritativeText: 'Bhaishajya Ratnavali (First Schedule to D&C Act 1940)',
    chapterSection: 'Kasa Rogadhikara',
    primaryIngredients: ['Abhraka Bhasma', 'Gandhaka', 'Vanga Bhasma', 'Parada', 'Haratala', 'Tamra Bhasma', 'Karpura', 'Jatiphala', 'Vriddhadaru'],
    dosageForm: 'Vati / Rasa (Herbo-mineral Tablet)',
    classicalIndication: 'Kasa (Cough), Shvasa (Asthma), Rajayakshma (Tuberculosis), Gala-roga (Throat disorders)',
    isClassicalGeneric: true
  },
  {
    id: 'avipattikar-churna',
    name: 'Avipattikar Churna',
    sanskritName: 'अविपत्तिकर चूर्ण',
    authoritativeText: 'Bhaishajya Ratnavali (First Schedule)',
    chapterSection: 'Amlapitta Rogadhikara',
    primaryIngredients: ['Trikatu', 'Triphala', 'Musta', 'Vidanga', 'Ela', 'Tejapatra', 'Lavanga', 'Trivrit', 'Sita (Sugar)'],
    dosageForm: 'Churna (Powder)',
    classicalIndication: 'Amlapitta (Hyperacidity), Vibandha (Constipation), Agnimandya',
    isClassicalGeneric: true
  },
  {
    id: 'hingwashtak-churna',
    name: 'Hingwashtak Churna',
    sanskritName: 'हिंग्वष्टक चूर्ण',
    authoritativeText: 'Ashtanga Hridayam / Bhaishajya Ratnavali (First Schedule)',
    chapterSection: 'Chikitsasthana / Agnimandya Rogadhikara',
    primaryIngredients: ['Sunthi', 'Maricha', 'Pippali', 'Ajamoda', 'Saindhava Lavana', 'Jeeraka', 'Krishna Jeeraka', 'Hingu (Asafoetida)'],
    dosageForm: 'Churna (Powder)',
    classicalIndication: 'Agnimandya (Loss of appetite), Vataja Grahani, Gulma, Shula (Colic)',
    isClassicalGeneric: true
  },
  {
    id: 'sudarshan-ghan-vati',
    name: 'Sudarshan Ghan Vati',
    sanskritName: 'सुदर्शन घन वटी',
    authoritativeText: 'Sahasrayogam / Sharangadhara Samhita (First Schedule)',
    chapterSection: 'Jwara Chikitsa (Derived from Maha Sudarshana Churna)',
    primaryIngredients: ['Kiratatikta (Swertia chirata)', 'Triphala', 'Haridra', 'Daruharidra', 'Kantakari', 'Guduchi', 'Parpata', 'Musta', 'Pippali'],
    dosageForm: 'Ghan Vati (Extract Tablet)',
    classicalIndication: 'Sarva Jwara (All types of fevers), Yakrit Pliha Vriddhi (Hepatosplenomegaly), Vishama Jwara',
    isClassicalGeneric: true
  },
  {
    id: 'shankhvati',
    name: 'Shankhvati',
    sanskritName: 'शंखवटी',
    authoritativeText: 'Bhaishajya Ratnavali (First Schedule)',
    chapterSection: 'Agnimandya Rogadhikara',
    primaryIngredients: ['Shankha Bhasma', 'Pancha Lavana', 'Hingu', 'Trikatu', 'Kshara (Yavakshara)', 'Chincha Bhasma', 'Parada', 'Gandhaka', 'Vatsanabha'],
    dosageForm: 'Vati (Tablet)',
    classicalIndication: 'Agnimandya, Ajeerna (Indigestion), Grahani, Shula',
    isClassicalGeneric: true
  },
  {
    id: 'agnitundi-vati',
    name: 'Agnitundi Vati',
    sanskritName: 'अग्नितुण्डी वटी',
    authoritativeText: 'Bhaishajya Ratnavali (First Schedule)',
    chapterSection: 'Agnimandya Rogadhikara',
    primaryIngredients: ['Parada', 'Gandhaka', 'Vatsanabha', 'Ajmod', 'Haritaki', 'Bibhitaki', 'Amalaki', 'Swarjika Kshara', 'Yava Kshara', 'Vidhara', 'Kupilu (Strychnos nux-vomica)'],
    dosageForm: 'Vati (Tablet)',
    classicalIndication: 'Agnimandya, Ajeerna, Udararoga, Vata-Nadi Vikara (Neurological issues)',
    isClassicalGeneric: true
  },
  {
    id: 'saptamrit-lauh',
    name: 'Saptamrit Lauh',
    sanskritName: 'सप्तामृत लौह',
    authoritativeText: 'Bhaishajya Ratnavali (First Schedule)',
    chapterSection: 'Netra Rogadhikara',
    primaryIngredients: ['Haritaki', 'Bibhitaki', 'Amalaki', 'Yashtimadhu', 'Lauha Bhasma'],
    dosageForm: 'Vati / Churna with Bhasma',
    classicalIndication: 'Timira (Cataract/Vision disorders), Netra Roga, Pandu, Amlapitta',
    isClassicalGeneric: true
  },
  {
    id: 'navayasa-lauh',
    name: 'Navayasa Lauh',
    sanskritName: 'नवायस लौह',
    authoritativeText: 'Charaka Samhita / Bhaishajya Ratnavali (First Schedule)',
    chapterSection: 'Chikitsasthana Chapter 16',
    primaryIngredients: ['Sunthi', 'Maricha', 'Pippali', 'Haritaki', 'Bibhitaki', 'Amalaki', 'Musta', 'Vidanga', 'Chitraka', 'Lauha Bhasma (9 parts)'],
    dosageForm: 'Churna / Vati',
    classicalIndication: 'Pandu (Anemia), Kamala (Jaundice), Hridroga, Prameha',
    isClassicalGeneric: true
  },
  {
    id: 'dhatri-lauh',
    name: 'Dhatri Lauh',
    sanskritName: 'धात्री लौह',
    authoritativeText: 'Bhaishajya Ratnavali (First Schedule)',
    chapterSection: 'Shula Rogadhikara',
    primaryIngredients: ['Dhatri (Amalaki)', 'Lauha Bhasma', 'Yashtimadhu', 'Guduchi'],
    dosageForm: 'Vati / Churna',
    classicalIndication: 'Shula (Gastric colic), Amlapitta, Pandu, Kamala',
    isClassicalGeneric: true
  },
  {
    id: 'vasavaleha',
    name: 'Vasavaleha',
    sanskritName: 'वासावलेह',
    authoritativeText: 'Bhaishajya Ratnavali (First Schedule)',
    chapterSection: 'Rajayakshma Rogadhikara',
    primaryIngredients: ['Vasa Swarasa / Kwatha', 'Sita (Sugar)', 'Ghrita', 'Pippali', 'Madhu (Honey)'],
    dosageForm: 'Avaleha / Lehya (Herbal Jam)',
    classicalIndication: 'Kasa (Cough), Shvasa (Asthma), Raktapitta, Rajayakshma',
    isClassicalGeneric: true
  },
  {
    id: 'pippalyasava',
    name: 'Pippalyasava',
    sanskritName: 'पिप्पल्यासव',
    authoritativeText: 'Bhaishajya Ratnavali (First Schedule)',
    chapterSection: 'Grahani Rogadhikara',
    primaryIngredients: ['Pippali', 'Maricha', 'Chavya', 'Haridra', 'Chitraka', 'Ghan (Musta)', 'Vidanga', 'Draksha', 'Dhataki', 'Jaggery'],
    dosageForm: 'Asava (Fermented Liquid)',
    classicalIndication: 'Grahani (IBS), Kasa, Shvasa, Arsha, Aruchi',
    isClassicalGeneric: true
  },
  {
    id: 'parthadyarishta',
    name: 'Parthadyarishta',
    sanskritName: 'पार्थाद्यारिष्ट (अर्जुनारिष्ट)',
    authoritativeText: 'Bhaishajya Ratnavali (First Schedule)',
    chapterSection: 'Hridroga Rogadhikara',
    primaryIngredients: ['Partha (Arjuna)', 'Mridvika (Draksha)', 'Madhuka (Mahua)', 'Dhataki', 'Jaggery'],
    dosageForm: 'Arishta (Fermented Liquid)',
    classicalIndication: 'Hridroga (Heart diseases), Phupphusa Roga (Lung diseases), Balya',
    isClassicalGeneric: true
  },
  {
    id: 'balarishtam',
    name: 'Balarishtam',
    sanskritName: 'बलारिष्ट',
    authoritativeText: 'Bhaishajya Ratnavali (First Schedule)',
    chapterSection: 'Vatavyadhi Rogadhikara',
    primaryIngredients: ['Bala', 'Ashwagandha', 'Eranda', 'Rasna', 'Ela', 'Prasarini', 'Lavanga', 'Usira', 'Dhataki', 'Jaggery'],
    dosageForm: 'Arishta (Fermented Liquid)',
    classicalIndication: 'Vatavyadhi, Balya, Agnimandya, Daurbalya',
    isClassicalGeneric: true
  },
  {
    id: 'bilvadi-churna',
    name: 'Bilvadi Churna',
    sanskritName: 'बिल्वादि चूर्ण',
    authoritativeText: 'Bhaishajya Ratnavali / Sharangadhara Samhita (First Schedule)',
    chapterSection: 'Grahani Rogadhikara',
    primaryIngredients: ['Bilva', 'Dhataki', 'Kutaja', 'Musta', 'Shunthi', 'Mocharasa'],
    dosageForm: 'Churna (Powder)',
    classicalIndication: 'Atisara (Diarrhea), Grahani (IBS), Pravahika (Dysentery)',
    isClassicalGeneric: true
  },
  {
    id: 'vyoshadi-vati',
    name: 'Vyoshadi Vati',
    sanskritName: 'व्योषादि वटी',
    authoritativeText: 'Ashtanga Hridayam (First Schedule)',
    chapterSection: 'Chikitsasthana Chapter 3',
    primaryIngredients: ['Vyosha (Trikatu)', 'Talisapatra', 'Amlavetasa', 'Chavya', 'Jeeraka', 'Twak', 'Ela', 'Jaggery'],
    dosageForm: 'Vati (Tablet / Lozenge)',
    classicalIndication: 'Peenasa (Coryza), Kasa, Shvasa, Aruchi, Swarabheda (Hoarseness)',
    isClassicalGeneric: true
  },
  {
    id: 'panchasakar-churna',
    name: 'Panchasakar Churna',
    sanskritName: 'पञ्चसकार चूर्ण',
    authoritativeText: 'Ayurveda Sara Sangraha',
    chapterSection: 'Churna Prakarana',
    primaryIngredients: ['Swarnapatri (Senna)', 'Shunthi', 'Shatapushpa (Fennel)', 'Saindhava Lavana', 'Shiva (Haritaki)'],
    dosageForm: 'Churna (Powder)',
    classicalIndication: 'Vibandha (Constipation), Udararoga, Amavata',
    isClassicalGeneric: true
  },
  {
    id: 'jatyadi-taila',
    name: 'Jatyadi Taila',
    sanskritName: 'जात्यादि तैल',
    authoritativeText: 'Sharangadhara Samhita (First Schedule)',
    chapterSection: 'Madhyama Khanda Chapter 9',
    primaryIngredients: ['Jati patra', 'Nimba', 'Patola', 'Karanja', 'Haridra', 'Daruharidra', 'Katuki', 'Manjistha', 'Tuttha', 'Tila Taila'],
    dosageForm: 'Taila (Medicated Oil for topical use)',
    classicalIndication: 'Nadi Vrana (Sinus ulcers), Sphota (Blisters), Kacchu (Itching), Kustha',
    isClassicalGeneric: true
  },
  {
    id: 'shadbindu-taila',
    name: 'Shadbindu Taila',
    sanskritName: 'षडबिन्दु तैल',
    authoritativeText: 'Bhaishajya Ratnavali (First Schedule)',
    chapterSection: 'Shiroroga Rogadhikara',
    primaryIngredients: ['Eranda Mula', 'Tagara', 'Shatapushpa', 'Jivanti', 'Rasna', 'Saindhava', 'Bhringaraja', 'Tila Taila', 'Aja Kshira'],
    dosageForm: 'Taila (Medicated Oil for Nasya)',
    classicalIndication: 'Shiroroga (Headaches), Khalitya (Hair fall), Palitya (Premature greying), Urdhvajatrugata Roga',
    isClassicalGeneric: true
  },
  {
    id: 'anu-taila',
    name: 'Anu Taila',
    sanskritName: 'अणु तैल',
    authoritativeText: 'Charaka Samhita (First Schedule)',
    chapterSection: 'Sutrasthana Chapter 5',
    primaryIngredients: ['Jivanti', 'Jalad (Musta)', 'Devadaru', 'Jal (Hrivera)', 'Twak', 'Usira', 'Gopi (Sariva)', 'Daruharidra', 'Tila Taila', 'Aja Kshira'],
    dosageForm: 'Taila (Medicated Oil for Nasya)',
    classicalIndication: 'Indriya Daurbalya (Sensory weakness), Shiroroga, Manyastambha (Neck stiffness), Peenasa',
    isClassicalGeneric: true
  },
  {
    id: 'shatavari-ghrita',
    name: 'Shatavari Ghrita',
    sanskritName: 'शतावरी घृत',
    authoritativeText: 'Bhaishajya Ratnavali (First Schedule)',
    chapterSection: 'Amlapitta Rogadhikara / Mutrakrichchhra',
    primaryIngredients: ['Shatavari Swarasa / Kwatha', 'Ksheera (Milk)', 'Ghrita (Ghee)', 'Jivaniya Gana herbs'],
    dosageForm: 'Ghrita (Medicated Ghee)',
    classicalIndication: 'Amlapitta, Raktapitta, Mutrakrichchhra, Vata-Pitta Vikara, Shukrakshaya',
    isClassicalGeneric: true
  },
  {
    id: 'phala-ghrita',
    name: 'Phala Ghrita',
    sanskritName: 'फल घृत',
    authoritativeText: 'Bhaishajya Ratnavali (First Schedule)',
    chapterSection: 'Yoni Vyapad Rogadhikara',
    primaryIngredients: ['Triphala', 'Shatavari', 'Kustha', 'Tagara', 'Vacha', 'Haridra', 'Ashwagandha', 'Ghrita', 'Milk'],
    dosageForm: 'Ghrita (Medicated Ghee)',
    classicalIndication: 'Yoni Vyapad (Vaginal disorders), Vandhyatva (Infertility), Garbhashaya Dosha, Sukradosha',
    isClassicalGeneric: true
  },
  {
    id: 'sukumara-kashayam',
    name: 'Sukumara Kashayam',
    sanskritName: 'सुकुमार कषाय',
    authoritativeText: 'Sahasrayogam / Ashtanga Hridayam (First Schedule)',
    chapterSection: 'Kashaya Prakarana',
    primaryIngredients: ['Punarnava', 'Dashamula', 'Payasya', 'Ashwagandha', 'Eranda', 'Shatavari', 'Darbha'],
    dosageForm: 'Kashayam (Decoction)',
    classicalIndication: 'Gulma, Vata-Roga, Udararoga, Yoni Roga, Vardhma (Hernia)',
    isClassicalGeneric: true
  },
  {
    id: 'punarnavadi-kashayam',
    name: 'Punarnavadi Kashayam',
    sanskritName: 'पुनर्नवादि कषाय',
    authoritativeText: 'Sahasrayogam (First Schedule)',
    chapterSection: 'Kashaya Prakarana',
    primaryIngredients: ['Punarnava', 'Nimba', 'Patola', 'Sunthi', 'Tikta (Katuki)', 'Amrita (Guduchi)', 'Darvi (Daruharidra)', 'Abhaya (Haritaki)'],
    dosageForm: 'Kashayam (Decoction)',
    classicalIndication: 'Sarvanga Shotha (Generalized edema), Udararoga, Pandu, Kasa',
    isClassicalGeneric: true
  },
  {
    id: 'indukantam-kashayam',
    name: 'Indukantam Kashayam',
    sanskritName: 'इन्दुकान्त कषाय',
    authoritativeText: 'Sahasrayogam (First Schedule)',
    chapterSection: 'Kashaya Prakarana',
    primaryIngredients: ['Putikaranja', 'Devadaru', 'Dashamula', 'Pippali', 'Chavya', 'Chitraka', 'Sunthi'],
    dosageForm: 'Kashayam (Decoction)',
    classicalIndication: 'Vata-Gulma, Shula, Jwara, Kshaya, Balya',
    isClassicalGeneric: true
  },
  {
    id: 'dhanwantaram-taila',
    name: 'Dhanwantaram Taila',
    sanskritName: 'धान्वन्तरं तैल',
    authoritativeText: 'Sahasrayogam / Ashtanga Hridayam (First Schedule)',
    chapterSection: 'Taila Prakarana',
    primaryIngredients: ['Bala (Sida cordifolia)', 'Yava', 'Kulattha', 'Dashamula', 'Tila Taila', 'Ksheera (Milk)'],
    dosageForm: 'Taila (Medicated Oil for external/internal)',
    classicalIndication: 'Vatavyadhi, Sutika Roga (Puerperal disorders), Balashosha (Emaciation)',
    isClassicalGeneric: true
  },
  {
    id: 'ksheerabala-taila',
    name: 'Ksheerabala Taila',
    sanskritName: 'क्षीरबला तैल',
    authoritativeText: 'Ashtanga Hridayam (First Schedule)',
    chapterSection: 'Chikitsasthana Chapter 21',
    primaryIngredients: ['Bala Kalka', 'Bala Kwatha', 'Ksheera (Cow milk)', 'Tila Taila'],
    dosageForm: 'Taila (Medicated Oil)',
    classicalIndication: 'Vatarakta, Vata-Vyadhi, Sukradhosha, Rasayana',
    isClassicalGeneric: true
  },
  {
    id: 'rasnadi-kashayam',
    name: 'Rasnadi Kashayam',
    sanskritName: 'रास्नादि कषाय',
    authoritativeText: 'Sahasrayogam (First Schedule)',
    chapterSection: 'Kashaya Prakarana',
    primaryIngredients: ['Rasna', 'Erandamula', 'Bala', 'Sahachara', 'Vari (Shatavari)', 'Guduchi', 'Amalaki', 'Sunthi'],
    dosageForm: 'Kashayam (Decoction)',
    classicalIndication: 'Vatavyadhi, Sandhigata Vata, Amavata',
    isClassicalGeneric: true
  },
  {
    id: 'varanadi-kashayam',
    name: 'Varanadi Kashayam',
    sanskritName: 'वरणादि कषाय',
    authoritativeText: 'Ashtanga Hridayam / Sahasrayogam (First Schedule)',
    chapterSection: 'Sutrasthana Chapter 15',
    primaryIngredients: ['Varuna', 'Sairyaka', 'Shatavari', 'Dahana (Chitraka)', 'Murva', 'Bilva', 'Brahmi', 'Karanja'],
    dosageForm: 'Kashayam (Decoction)',
    classicalIndication: 'Kapha-Medo Vikara (Obesity/Dyslipidemia), Gulma, Sirashula (Headache)',
    isClassicalGeneric: true
  },
  {
    id: 'maha-rasnadi-kashayam',
    name: 'Maha Rasnadi Kashayam',
    sanskritName: 'महारास्नादि कषाय',
    authoritativeText: 'Bhaishajya Ratnavali (First Schedule)',
    chapterSection: 'Vatavyadhi Rogadhikara',
    primaryIngredients: ['Rasna', 'Dhanvayasa', 'Bala', 'Eranda', 'Devadaru', 'Kachura', 'Vacha', 'Vasaka', 'Sunthi', 'Haritaki', 'Chavya', 'Musta', 'Punarnava', 'Guduchi'],
    dosageForm: 'Kashayam (Decoction)',
    classicalIndication: 'Sarvanga Vata, Pakshaghata (Hemiplegia), Gridhrasi (Sciatica), Sandhivata',
    isClassicalGeneric: true
  }
];
