import { EvidenceItem, Product } from '../src/types.js';

export const AUTHORITATIVE_CORPUS: EvidenceItem[] = [
  // ================= INDIA: PATENTS ACT & RULES =================
  {
    id: 'patents-act-3p',
    authority: 'Indian Patent Office (CGPDTM) / Ministry of Commerce & Industry',
    framework: 'The Patents Act, 1970 (as amended up to Patents Rules, 2024)',
    section: 'Section 3(p)',
    jurisdiction: 'INDIA',
    title: 'Traditional Knowledge Non-Patentability Bar',
    passage: 'The following are not inventions within the meaning of this Act: (p) an invention which in effect is traditional knowledge or which is an aggregation or duplication of known properties of traditionally known component or components. In Ayurvedic applications, combinations of herbs with known traditional uses cannot be patented as products unless non-obvious synergistic efficacy is experimentally demonstrated.',
    strength: 'HIGH',
    sourceUrl: 'https://ipindia.gov.in/writereaddata/Portal/IPOAct/1_31_1_patent-act-1970-11march2015.pdf#page=14',
    pageNumber: 14,
    pageRecord: 'Patents Act 1970, Section 3(p), p. 14',
    verificationStatus: 'VERIFIED_OFFICIAL',
    version: 'Act No. 39 of 1970 (Amended 2005 & Rules 2024)',
    effectiveDate: '2005-01-01',
    tags: ['patent', 'traditional knowledge', 'exclusion', 'section 3p', 'tkdl']
  },
  {
    id: 'patents-act-3e',
    authority: 'Indian Patent Office (CGPDTM)',
    framework: 'The Patents Act, 1970',
    section: 'Section 3(e)',
    jurisdiction: 'INDIA',
    title: 'Mere Admixture and Synergistic Demonstration Requirement',
    passage: 'The following are not inventions: (e) a substance obtained by a mere admixture resulting only in the aggregation of the properties of the components thereof or a process for producing such substance. To overcome this bar, the applicant must demonstrate synergistic therapeutic efficacy via quantitative comparative bioassays (e.g. Combination Index < 1 or statistically significant superiority over individual components).',
    strength: 'HIGH',
    sourceUrl: 'https://ipindia.gov.in/writereaddata/Portal/IPOAct/1_31_1_patent-act-1970-11march2015.pdf#page=13',
    pageNumber: 13,
    pageRecord: 'Patents Act 1970, Section 3(e), p. 13',
    verificationStatus: 'VERIFIED_OFFICIAL',
    version: 'Act No. 39 of 1970 & Guidelines for Examination in Pharmaceuticals',
    effectiveDate: '2014-10-29',
    tags: ['patent', 'synergy', 'mere admixture', 'section 3e', 'composition']
  },
  {
    id: 'patents-act-3d',
    authority: 'Indian Patent Office (CGPDTM) / Supreme Court of India',
    framework: 'The Patents Act, 1970',
    section: 'Section 3(d)',
    jurisdiction: 'INDIA',
    title: 'Enhancement of Known Efficacy Requirement for Known Substances',
    passage: 'The mere discovery of a new form of a known substance which does not result in the enhancement of the known efficacy of that substance, or the mere discovery of any new property or new use for a known substance, is not patentable. For herbal and natural products, isolated fractions or extracts must show therapeutic efficacy enhancement over standard crude extracts.',
    strength: 'HIGH',
    sourceUrl: 'https://ipindia.gov.in/writereaddata/Portal/IPOAct/1_31_1_patent-act-1970-11march2015.pdf#page=13',
    pageNumber: 13,
    pageRecord: 'Patents Act 1970, Section 3(d), p. 13',
    verificationStatus: 'VERIFIED_OFFICIAL',
    version: 'Act No. 39 of 1970 (Section 3(d))',
    effectiveDate: '2005-01-01',
    tags: ['patent', 'efficacy', 'new form', 'section 3d']
  },
  {
    id: 'patents-act-10-4',
    authority: 'Indian Patent Office (CGPDTM)',
    framework: 'The Patents Act, 1970 & Patent Rules, 2024',
    section: 'Section 10(4)(ii)(D) & Rule 24C',
    jurisdiction: 'INDIA',
    title: 'Mandatory Disclosure of Biological Source & NBA Permission',
    passage: 'The specification must disclose the source and geographical origin of the biological material in the specification, when used in an invention. Furthermore, if biological material obtained from India is used, the applicant must obtain the approval of the National Biodiversity Authority (NBA) under Section 6 of the Biological Diversity Act before the grant of the patent.',
    strength: 'HIGH',
    sourceUrl: 'https://ipindia.gov.in/writereaddata/Portal/IPOAct/1_31_1_patent-act-1970-11march2015.pdf#page=23',
    pageNumber: 23,
    pageRecord: 'Patents Act 1970, Section 10(4)(ii)(D), p. 23',
    verificationStatus: 'VERIFIED_OFFICIAL',
    version: 'Patents (Amendment) Rules, 2024',
    effectiveDate: '2024-03-15',
    tags: ['patent', 'disclosure', 'source', 'nba', 'biological diversity']
  },

  // ================= INDIA: BIOLOGICAL DIVERSITY ACT (2002/2023/2024) =================
  {
    id: 'bda-section-3',
    authority: 'National Biodiversity Authority (NBA) / MoEFCC',
    framework: 'Biological Diversity Act, 2002 (amended by BD (Amendment) Act, 2023)',
    section: 'Section 3 & Section 4',
    jurisdiction: 'INDIA',
    title: 'Certain Persons Not to Undertake Biodiversity-Related Activities Without Approval',
    passage: 'No person who is not a citizen of India, or a citizen who is an NRI, or a body corporate, association or organization incorporated or registered in India having foreign investment or management, shall obtain any biological resource occurring in India or knowledge associated thereto for research or for commercial utilization, without previous approval of the National Biodiversity Authority (Form 1).',
    strength: 'HIGH',
    sourceUrl: 'https://nbaindia.org/uploaded/act/Biological_Diversity_Act_2002.pdf#page=4',
    pageNumber: 4,
    pageRecord: 'Biological Diversity Act 2002, Section 3, p. 4',
    verificationStatus: 'VERIFIED_OFFICIAL',
    version: 'Biological Diversity Rules 2024 / Act 2023',
    effectiveDate: '2024-01-01',
    tags: ['abs', 'nba', 'foreign entity', 'section 3', 'approval']
  },
  {
    id: 'bda-section-6',
    authority: 'National Biodiversity Authority (NBA)',
    framework: 'Biological Diversity Act, 2002 & Biological Diversity Rules, 2024',
    section: 'Section 6 & Rule 18 (Form 3)',
    jurisdiction: 'INDIA',
    title: 'Application for Intellectual Property Rights on Biological Resources',
    passage: 'No person shall apply for any intellectual property right, by whatever name called, in or outside India for any invention based on any research or information on a biological resource obtained from India without obtaining previous approval of the National Biodiversity Authority before grant of the patent. Under the 2024 Rules, an application in Form 3 must be filed; benefit sharing is calculated at 0.1% to 0.5% of ex-factory commercial sales or mutually agreed terms.',
    strength: 'HIGH',
    sourceUrl: 'https://nbaindia.org/uploaded/act/Biological_Diversity_Act_2002.pdf#page=5',
    pageNumber: 5,
    pageRecord: 'Biological Diversity Act 2002, Section 6, p. 5',
    verificationStatus: 'VERIFIED_OFFICIAL',
    version: 'BDA Rules 2024, Rule 18',
    effectiveDate: '2024-03-01',
    tags: ['abs', 'nba', 'ipr', 'form 3', 'benefit sharing', 'section 6']
  },
  {
    id: 'bda-section-7-exemption',
    authority: 'National Biodiversity Authority (NBA) / Ministry of Ayush',
    framework: 'Biological Diversity (Amendment) Act, 2023 & Clarification Orders',
    section: 'Section 7 Proviso & Section 40',
    jurisdiction: 'INDIA',
    title: 'Exemptions for Local Vaidyas, Registered AYUSH Practitioners & Cultivated Plants',
    passage: 'Under the 2023 Amendment to the Biological Diversity Act, registered AYUSH practitioners (Vaidyas, Hakims) and local people practicing indigenous medicine are exempted from prior intimation to State Biodiversity Boards (SBBs) for accessing biological resources for their own dispensing and treatment. Furthermore, cultivated medicinal plants (with verifiable origin certification) are accorded simplified pathways without predatory access levies.',
    strength: 'HIGH',
    sourceUrl: 'https://egazette.gov.in/WriteReadData/2023/247854.pdf#page=3',
    pageNumber: 3,
    pageRecord: 'Biological Diversity (Amendment) Act 2023, Section 7 Proviso, p. 3',
    verificationStatus: 'VERIFIED_OFFICIAL',
    version: 'Act No. 10 of 2023',
    effectiveDate: '2023-08-01',
    tags: ['abs', 'ayush', 'vaidya', 'exemption', 'cultivated', 'sbb']
  },

  // ================= INDIA: DRUGS & COSMETICS ACT (ASU REGIME) =================
  {
    id: 'dc-act-3a-3h',
    authority: 'Ministry of Ayush / Central Drugs Standard Control Organization (CDSCO)',
    framework: 'Drugs and Cosmetics Act, 1940 & Rules, 1945',
    section: 'Section 3(a) & Section 3(h)',
    jurisdiction: 'INDIA',
    title: 'Definitions of Classical vs Patent/Proprietary (P&P) ASU Medicines',
    passage: 'Section 3(a) defines Ayurvedic, Siddha or Unani drugs as including only substances manufactured exclusively in accordance with formulae described in the authoritative books of ASU systems specified in the First Schedule. Section 3(h) defines Patent or Proprietary medicine in relation to ASU systems as a formulation containing ingredients entirely mentioned in First Schedule texts but with a recipe, ratio or combination not strictly identical to a classical yoga.',
    strength: 'HIGH',
    sourceUrl: 'https://cdsco.gov.in/opencms/export/sites/CDSCO_WEB/Pdf-documents/acts_rules/2016DrugsandCosmeticsAct1940Rules1945.pdf#page=11',
    pageNumber: 11,
    pageRecord: 'Drugs and Cosmetics Act 1940, Section 3(a) & 3(h), p. 11',
    verificationStatus: 'VERIFIED_OFFICIAL',
    version: 'Act No. 23 of 1940 (Chapter IV-A)',
    effectiveDate: '1940-04-10',
    tags: ['regulatory', 'ayush', 'classical', 'proprietary', 'section 3h']
  },
  {
    id: 'dc-rules-158b',
    authority: 'Ministry of Ayush (Ayurvedic, Siddha and Unani Drugs Technical Advisory Board)',
    framework: 'Drugs and Cosmetics Rules, 1945',
    section: 'Rule 158-B',
    jurisdiction: 'INDIA',
    title: 'Licensing Requirements & Evidence Guidelines for ASU Medicines',
    passage: 'Rule 158-B classifies proof of effectiveness and safety required for ASU licenses into: (I) Classical generic drugs: only authoritative text citation required, clinical trials not needed; (II) Patent & Proprietary ASU drugs: safety data (acute oral toxicity study according to OECD guidelines) plus published authoritative literature; clinical trials required only if the drug is prescribed for a new indication; (III) New ASU Drugs: extensive preclinical animal toxicity plus human clinical trials as per Schedule Y principles.',
    strength: 'HIGH',
    sourceUrl: 'https://ayush.gov.in/docs/drugs-cosmetics-rules.pdf#page=5',
    pageNumber: 5,
    pageRecord: 'Drugs and Cosmetics Rules 1945, Rule 158-B (Notification GSR 560(E)), p. 5',
    verificationStatus: 'VERIFIED_OFFICIAL',
    version: 'Notification G.S.R. 560(E)',
    effectiveDate: '2010-08-10',
    tags: ['regulatory', 'licensing', 'rule 158b', 'safety data', 'clinical trials']
  },
  {
    id: 'phytopharmaceutical-regulations',
    authority: 'CDSCO / Ministry of Health & Family Welfare',
    framework: 'Drugs and Cosmetics Rules, 1945',
    section: 'Rule 122-E & Schedule Y (Appendix I-B)',
    jurisdiction: 'INDIA',
    title: 'Phytopharmaceutical Drugs Regulatory Pathway',
    passage: 'A Phytopharmaceutical drug is defined as a purified and standardized fraction with defined minimum four bioactive or phytochemical marker compounds of an extract of a medicinal plant or its part, for internal or external use of human beings or animals. It requires regulatory approval from the DCGI (Central Licensing Authority) with comprehensive chemical fingerprinting, stability studies, toxicology, and Phase I-III clinical development.',
    strength: 'HIGH',
    sourceUrl: 'https://cdsco.gov.in/opencms/export/sites/CDSCO_WEB/Pdf-documents/acts_rules/Gazette_Notification_Phytopharmaceutical.pdf#page=2',
    pageNumber: 2,
    pageRecord: 'Gazette Notification GSR 918(E), Rule 122-E & Schedule Y, p. 2',
    verificationStatus: 'VERIFIED_OFFICIAL',
    version: 'G.S.R. 918(E) Phytopharmaceutical Amendment',
    effectiveDate: '2015-11-30',
    tags: ['regulatory', 'phytopharmaceutical', 'standardization', 'dcgi', 'clinical trial']
  },

  // ================= INDIA: AYURVEDA AAHAR & ADVERTISING =================
  {
    id: 'fssai-ayurveda-aahar-2022',
    authority: 'Food Safety and Standards Authority of India (FSSAI) & Ministry of Ayush',
    framework: 'Food Safety and Standards (Ayurveda Aahar) Regulations, 2022',
    section: 'Regulations 3, 4, 5 & Schedule I/II',
    jurisdiction: 'INDIA',
    title: 'Ayurveda Aahar (Food) Standards and Disease Claim Prohibitions',
    passage: 'Ayurveda Aahar covers food prepared in accordance with recipes or ingredients described in authoritative Ayurvedic texts, meant for daily consumption for physiological well-being. Prohibitions: No manufacturer shall describe an Ayurveda Aahar as capable of treating, curing, or preventing any human disease. Only health promotion, Rasayana, and physiological balance claims are permitted. Labelling must feature the dedicated Ayurveda Aahar logo and advisory statements.',
    strength: 'HIGH',
    sourceUrl: 'https://fssai.gov.in/upload/notifications/2022/05/627a3f4caef0bGazette_Notification_Ayurveda_Aahar_09_05_2022.pdf#page=4',
    pageNumber: 4,
    pageRecord: 'FSSAI Gazette F. No. Std/SP-05/A-1.2022/N-01, Reg. 3-5, p. 4',
    verificationStatus: 'VERIFIED_OFFICIAL',
    version: 'Gazette Notification F. No. Std/SP-05/A-1.2022/N-01',
    effectiveDate: '2022-05-05',
    tags: ['regulatory', 'fssai', 'ayurveda aahar', 'nutraceutical', 'food', 'claims prohibition']
  },
  {
    id: 'dmr-act-1954',
    authority: 'Ministry of Health & Family Welfare / State Drug Controllers',
    framework: 'Drugs and Magic Remedies (Objectionable Advertisements) Act, 1954',
    section: 'Section 3 & Schedule',
    jurisdiction: 'INDIA',
    title: 'Absolute Prohibition of Advertisements for Specified Diseases',
    passage: 'No person shall take part in the publication of any advertisement referring to any drug which suggests or leads to the use of that drug for diagnosis, cure, mitigation, treatment or prevention of 54 specified conditions/diseases in the Schedule, including arthritis/rheumatism, diabetes, hypertension, cancer, sexual disorders, asthma, and kidney disorders. Direct marketing making curative claims on these conditions is a cognizable criminal offense.',
    strength: 'HIGH',
    sourceUrl: 'https://legislative.gov.in/sites/default/files/A1954-21_0.pdf#page=2',
    pageNumber: 2,
    pageRecord: 'DMR Act 1954, Section 3 & Schedule, p. 2',
    verificationStatus: 'VERIFIED_OFFICIAL',
    version: 'Act No. 21 of 1954',
    effectiveDate: '1955-04-01',
    tags: ['regulatory', 'advertising', 'dmr act', 'prohibition', 'joint disorders', 'diabetes']
  },

  // ================= INDIA: TRADEMARKS, GI & DESIGNS =================
  {
    id: 'tm-act-section-9',
    authority: 'Trade Marks Registry (CGPDTM)',
    framework: 'Trade Marks Act, 1999',
    section: 'Section 9(1)(b) & Section 9(1)(c)',
    jurisdiction: 'INDIA',
    title: 'Prohibition on Registering Descriptive Ayurvedic & Sanskrit Botanical Names',
    passage: 'Marks which consist exclusively of signs or indications which may serve in trade to designate the kind, quality, intended purpose, or other characteristics of the goods, or which have become customary in current language, shall not be registered. Classical Sanskrit formulation names (e.g. "Chyawanprash", "Triphala", "Ashwagandha") are generic publici juris and cannot be registered as individual proprietary trademarks in Class 5 or Class 3.',
    strength: 'HIGH',
    sourceUrl: 'https://ipindia.gov.in/writereaddata/Portal/IPOAct/1_43_1_trade-marks-act.pdf#page=11',
    pageNumber: 11,
    pageRecord: 'Trade Marks Act 1999, Section 9(1)(b), p. 11',
    verificationStatus: 'VERIFIED_OFFICIAL',
    version: 'Act No. 47 of 1999',
    effectiveDate: '2003-09-15',
    tags: ['trademark', 'section 9', 'descriptive', 'sanskrit', 'generic', 'class 5']
  },
  {
    id: 'gi-act-1999',
    authority: 'Geographical Indications Registry (CGPDTM)',
    framework: 'Geographical Indications of Goods (Registration and Protection) Act, 1999',
    section: 'Section 8 & Section 11',
    jurisdiction: 'INDIA',
    title: 'Protection of Agro-Climatic Botanical Varieties and Traditional Formulations',
    passage: 'GI registration protects goods originating in a defined geographical territory where a given quality, reputation, or other characteristic of the good is attributable to its geographical origin. Examples in the herbal domain include Malabar Pepper (GI #49), Alleppey Green Cardamom (GI #65), Navara Rice (GI #115 - used in Shashtika Shali Pinda Sweda), and Kashmir Saffron (GI #635). Individual entities cannot claim exclusive trademark rights over registered GI terms.',
    strength: 'HIGH',
    sourceUrl: 'https://ipindia.gov.in/writereaddata/Portal/IPOAct/1_44_1_GI_Act_1999.pdf#page=5',
    pageNumber: 5,
    pageRecord: 'GI of Goods Act 1999, Section 8 & 11, p. 5',
    verificationStatus: 'VERIFIED_OFFICIAL',
    version: 'Act No. 48 of 1999',
    effectiveDate: '2003-09-15',
    tags: ['gi', 'geographical indication', 'kashmir saffron', 'malabar pepper', 'navara']
  },
  {
    id: 'ppvfr-act-2001',
    authority: 'Protection of Plant Varieties and Farmers\' Rights Authority (PPV&FRA) / Ministry of Agriculture',
    framework: 'Protection of Plant Varieties and Farmers\' Rights Act, 2001 & Rules, 2003',
    section: 'Section 14, Section 15, Section 16, Section 39(1)(iv) & Section 30',
    jurisdiction: 'INDIA',
    title: 'Plant Variety Protection for Medicinal & Aromatic Cultivars',
    passage: 'The PPVFR Act provides sui generis plant variety protection for new, extant, and farmers\' varieties of plants including medicinal and aromatic species. Section 14 permits registration of new plant varieties with novelty, distinctness, uniformity, and stability (DUS). Section 15 covers extant varieties (including traditional landraces of Ashwagandha, Shatavari, Tulasi cultivars) already notified under Seeds Act. Section 39(1)(iv) protects farmers\' right to save, use, sow, resow, exchange, share, or sell farm produce of a protected variety (but not sell branded seed). Section 30 grants researchers\' rights to use registered varieties for developing new varieties. For Ayurvedic raw material producers and herbal cultivators, PPVFR registration of improved cultivars (e.g. high-withanolide Ashwagandha cv. "Pratap Shweta", high-curcumin Curcuma longa cv. "Pratibha") provides 15-year (extant) to 18-year (new variety) exclusive commercial propagation rights. This is distinct from patent protection and can coexist with GI registration for agro-climatic varieties.',
    strength: 'HIGH',
    sourceUrl: 'https://plantauthority.gov.in/sites/default/files/PPVFR_Act_2001.pdf#page=9',
    pageNumber: 9,
    pageRecord: 'PPV&FR Act 2001, Section 14-16 & 39, p. 9',
    verificationStatus: 'VERIFIED_OFFICIAL',
    version: 'Act No. 53 of 2001 & PPV&FR Rules 2003',
    effectiveDate: '2005-11-11',
    tags: ['plant variety', 'ppvfr', 'cultivar', 'farmers rights', 'dus', 'medicinal plants', 'seed']
  },
  {
    id: 'trade-secrets-india',
    authority: 'Indian Courts (Common Law) / WTO TRIPS Council',
    framework: 'Indian Contract Act 1872 (Section 27), TRIPS Agreement Article 39, Information Technology Act 2000 (Section 72)',
    section: 'Common Law Confidentiality, TRIPS Art 39.2 & IT Act Section 72',
    jurisdiction: 'INDIA',
    title: 'Trade Secret Protection for Proprietary Ayurvedic Manufacturing Processes',
    passage: 'India has no dedicated trade secret statute; protection rests on common law principles of breach of confidence, contractual Non-Disclosure Agreements (NDAs), and equity jurisdiction. Under TRIPS Article 39.2, India is obligated to protect undisclosed information that (a) is secret, (b) has commercial value because it is secret, and (c) has been subject to reasonable steps to keep it secret. For Ayurvedic manufacturers, proprietary Shodhana (purification) protocols, specific fermentation parameters for Asava/Arishta, unique Bhasma Marana (incineration) temperature-time profiles, and standardized extraction ratios are protectable as trade secrets provided they are documented with restricted access, employee NDAs are enforced, and visitor/consultant confidentiality agreements are in place. The IT Act Section 72 criminalizes unauthorized disclosure of information accessed under contractual obligation. Key precedent: John Richard Brady v. Chemical Process Equipments (1987 Delhi HC) established that manufacturing know-how qualifies for injunctive relief against misappropriation. Trade secret protection complements (and does not conflict with) patent filing — an MSME may patent a novel extraction process while keeping fermentation starter culture composition as a trade secret.',
    strength: 'MEDIUM',
    sourceUrl: 'https://www.wto.org/english/docs_e/legal_e/27-trips_04d_e.htm#39',
    pageNumber: 1,
    pageRecord: 'WTO TRIPS Agreement Art. 39.2 & Indian Contract Act Sec. 27',
    verificationStatus: 'VERIFIED_OFFICIAL',
    version: 'TRIPS Agreement 1994, Art 39; Indian Contract Act 1872',
    effectiveDate: '1995-01-01',
    tags: ['trade secret', 'nda', 'confidentiality', 'trips article 39', 'undisclosed information', 'proprietary process']
  },

  // ================= INTERNATIONAL: WIPO, CBD, NAGOYA, TRIPS =================
  {
    id: 'wipo-gratk-treaty-2024',
    authority: 'World Intellectual Property Organization (WIPO)',
    framework: 'WIPO Treaty on Intellectual Property, Genetic Resources and Associated Traditional Knowledge',
    section: 'Article 3, Article 4 & Article 17',
    jurisdiction: 'INTERNATIONAL',
    title: 'Genetic Resource / Traditional Knowledge Disclosure Treaty — Status-Aware Guidance',
    passage: 'The treaty was adopted in Geneva on May 24, 2024 and establishes disclosure obligations for patent applications based on genetic resources and associated traditional knowledge. However, the treaty is not yet in force: WIPO states that its entry into force will be notified after the required number of ratifications or accessions is reached. AyushIP Navigator therefore treats this as an international framework to track and prepare for, not as a universally binding current obligation.',
    strength: 'HIGH',
    sourceUrl: 'https://www.wipo.int/wipolex/en/treaties/notifications/details/treaty_gratk_3',
    pageNumber: 1,
    pageRecord: 'WIPO Treaty Notification GRATK/3, Articles 3 & 17',
    verificationStatus: 'VERIFIED_OFFICIAL',
    version: 'Status verified against WIPO notification, March 13, 2026',
    effectiveDate: '2024-05-24',
    tags: ['international', 'wipo', 'gratk', 'disclosure', 'treaty', 'traditional knowledge', 'not yet in force']
  },
  {
    id: 'cbd-nagoya-protocol',
    authority: 'United Nations Convention on Biological Diversity (CBD) Secretariat',
    framework: 'Convention on Biological Diversity (1992) & Nagoya Protocol on Access and Benefit-Sharing',
    section: 'CBD Article 15 & Nagoya Protocol Articles 5, 6 & 15',
    jurisdiction: 'INTERNATIONAL',
    title: 'Sovereignty over Genetic Resources, Prior Informed Consent (PIC) & Mutually Agreed Terms (MAT)',
    passage: 'States have sovereign rights over their natural resources. Access to genetic resources shall be subject to Prior Informed Consent (PIC) of the Contracting Party providing such resources. Benefits arising from commercial and other utilization of genetic resources and associated traditional knowledge must be shared in a fair and equitable manner upon Mutually Agreed Terms (MAT). Compliance certificates (IRCC) are tracked via the ABS Clearing-House.',
    strength: 'HIGH',
    sourceUrl: 'https://www.cbd.int/doc/legal/nagoya-protocol-en.pdf#page=6',
    pageNumber: 6,
    pageRecord: 'Nagoya Protocol on ABS, Articles 5, 6 & 15, p. 6',
    verificationStatus: 'VERIFIED_OFFICIAL',
    version: 'UNEP/CBD/COP/10/27',
    effectiveDate: '2014-10-12',
    tags: ['international', 'cbd', 'nagoya protocol', 'pic', 'mat', 'abs', 'benefit sharing']
  },
  {
    id: 'trips-article-27',
    authority: 'World Trade Organization (WTO)',
    framework: 'Agreement on Trade-Related Aspects of Intellectual Property Rights (TRIPS)',
    section: 'Article 27.1 & Article 27.3(b)',
    jurisdiction: 'INTERNATIONAL',
    title: 'Patentable Subject Matter and Exclusions for Natural Plants/Animals',
    passage: 'Article 27.1 provides that patents shall be available for any inventions, whether products or processes, in all fields of technology, provided that they are new, involve an inventive step and are capable of industrial application. Article 27.3(b) permits members to exclude from patentability plants and animals other than micro-organisms, and essentially biological processes for the production of plants or animals, but mandates the protection of plant varieties either by patents or by an effective sui generis system.',
    strength: 'HIGH',
    sourceUrl: 'https://www.wto.org/english/docs_e/legal_e/27-trips_04c_e.htm#27',
    pageNumber: 1,
    pageRecord: 'WTO TRIPS Agreement 1994, Article 27.1 & 27.3(b)',
    verificationStatus: 'VERIFIED_OFFICIAL',
    version: 'TRIPS Agreement 1994',
    effectiveDate: '1995-01-01',
    tags: ['international', 'trips', 'wto', 'patentability', 'plants exclusion']
  },
  {
    id: 'pct-madrid-hague',
    authority: 'World Intellectual Property Organization (WIPO)',
    framework: 'Patent Cooperation Treaty (PCT) & Madrid System for Trade Marks',
    section: 'PCT Chapter I/II & Madrid Protocol Article 2',
    jurisdiction: 'INTERNATIONAL',
    title: 'Unified International Filing Mechanisms for Patents and Trademarks',
    passage: 'The PCT allows filing a single international patent application to seek protection in up to 157 contracting states. International searching authorities (including the Indian Patent Office as ISA/IPEA) conduct prior art searches. Under the Madrid Protocol, a single international trademark application based on a home country application (e.g. Indian Trade Marks Registry) can be designated across 130 countries.',
    strength: 'HIGH',
    sourceUrl: 'https://www.wipo.int/pct/en/texts/articles/a15.html',
    pageNumber: 1,
    pageRecord: 'WIPO PCT Regulations & Madrid Protocol Art. 2',
    verificationStatus: 'VERIFIED_OFFICIAL',
    version: 'PCT Regulations as in force',
    effectiveDate: '2023-01-01',
    tags: ['international', 'pct', 'madrid system', 'international filing', 'isa']
  },

  // ================= INTERNATIONAL: EXPORT MARKETS =================
  {
    id: 'us-fda-dshea-herbal',
    authority: 'United States Food and Drug Administration (US FDA)',
    framework: 'Federal Food, Drug, and Cosmetic Act & DSHEA of 1994',
    section: '21 U.S.C. 343(r)(6) & 21 CFR Part 190.6 (NDI)',
    jurisdiction: 'INTERNATIONAL',
    title: 'US Herbal Product Classification: Dietary Supplements vs Botanical Drugs',
    passage: 'Herbal Ayurveda products entering the USA are primarily regulated as Dietary Supplements under DSHEA. If an ingredient was not marketed in the US prior to October 15, 1994, a New Dietary Ingredient (NDI) notification must be submitted to the FDA at least 75 days before commercial marketing. Claims: Disease treatment or cure claims are strictly prohibited and immediately convert the product into an unapproved new drug. Only Structure/Function claims with the mandatory FDA disclaimer are permitted.',
    strength: 'HIGH',
    sourceUrl: 'https://www.govinfo.gov/content/pkg/USCODE-2021-title21/pdf/USCODE-2021-title21-chap9-subchapIV-sec343.pdf#page=4',
    pageNumber: 4,
    pageRecord: '21 U.S.C. 343(r)(6) & 21 CFR Part 190.6 NDI, p. 4',
    verificationStatus: 'VERIFIED_OFFICIAL',
    version: 'Public Law 103-417 & 21 CFR 190',
    effectiveDate: '1994-10-15',
    tags: ['export', 'usa', 'fda', 'dshea', 'dietary supplement', 'ndi', 'claims']
  },
  {
    id: 'eu-thmpd-directive',
    authority: 'European Medicines Agency (EMA) / European Commission',
    framework: 'Directive 2004/24/EC amending Directive 2001/83/EC (THMPD)',
    section: 'Article 16a to 16i (Traditional Herbal Medicinal Products)',
    jurisdiction: 'INTERNATIONAL',
    title: 'EU Simplified Registration Scheme and 30/15-Year Traditional Use Hurdle',
    passage: 'The Traditional Herbal Medicinal Products Directive (THMPD) provides a simplified registration procedure for herbal medicinal products. Crucial requirement: The applicant must demonstrate that the product has had traditional medicinal use for at least 30 years preceding the application, of which at least 15 years must have been within the European Union. Products lacking 15 years of recorded European use cannot access this simplified pathway and must undergo full Well-Established Use (Article 10a) or Marketing Authorization.',
    strength: 'HIGH',
    sourceUrl: 'https://eur-lex.europa.eu/LexUriServ/LexUriServ.do?uri=OJ:L:2004:136:0085:0090:EN:PDF#page=2',
    pageNumber: 2,
    pageRecord: 'Directive 2004/24/EC, Article 16a to 16i, p. 2',
    verificationStatus: 'VERIFIED_OFFICIAL',
    version: 'Directive 2004/24/EC',
    effectiveDate: '2004-04-30',
    tags: ['export', 'eu', 'ema', 'thmpd', 'traditional herbal', '30 year rule']
  },
  {
    id: 'uk-mhra-thr',
    authority: 'UK Medicines and Healthcare products Regulatory Agency (MHRA)',
    framework: 'Human Medicines Regulations 2012 (Part 7)',
    section: 'Traditional Herbal Registration (THR) Scheme',
    jurisdiction: 'INTERNATIONAL',
    title: 'UK Traditional Herbal Medicines Framework Post-Brexit',
    passage: 'Following the UK’s withdrawal from the EU, the MHRA operates an independent THR scheme requiring demonstrated 30-year traditional medicinal use (with acceptable evidence from the UK, EU, or wider Commonwealth/India if scientifically substantiated), manufacturing according to UK GMP standards, and approved consumer leaflets containing appropriate safety cautions.',
    strength: 'HIGH',
    sourceUrl: 'https://www.legislation.gov.uk/uksi/2012/1916/part/7/made',
    pageNumber: 1,
    pageRecord: 'UK Statutory Instrument 2012 No. 1916, Part 7 THR',
    verificationStatus: 'VERIFIED_OFFICIAL',
    version: 'UK Statutory Instrument 2012 No. 1916',
    effectiveDate: '2021-01-01',
    tags: ['export', 'uk', 'mhra', 'thr', 'post brexit']
  },
  {
    id: 'uae-mohap-herbal',
    authority: 'UAE Ministry of Health and Prevention (MoHAP)',
    framework: 'Federal Law No. 4 of 1983 regarding the Pharmaceutical Profession and Institutions',
    section: 'Registration Guidelines for Herbal and Complementary Medicines',
    jurisdiction: 'INTERNATIONAL',
    title: 'UAE Registration for Ayurvedic and Herbal Preparations',
    passage: 'Ayurvedic formulations require registration as Complementary Medicines. Requirements include: Certificate of Free Sale (CoFS) issued by the Ministry of Ayush / State Licensing Authority in India, WHO-GMP certification of manufacturing facility, complete stability data (Zone IVa/IVb testing at 30°C/65% RH or 40°C/75% RH), heavy metal testing (lead, cadmium, arsenic, mercury within WHO limits), and pesticide/microbial clearance.',
    strength: 'HIGH',
    sourceUrl: 'https://mohap.gov.ae/en/services/issue-a-registration-certificate-for-herbal-and-complementary-medicine',
    pageNumber: 1,
    pageRecord: 'MoHAP Complementary Medicine Registration Guide 2022, Sec. 4',
    verificationStatus: 'VERIFIED_OFFICIAL',
    version: 'MoHAP Complementary Medicine Registration Guide 2022',
    effectiveDate: '2022-01-01',
    tags: ['export', 'uae', 'mohap', 'cofs', 'zone ivb', 'heavy metals']
  },
  {
    id: 'budapest-treaty-microorganism',
    authority: 'World Intellectual Property Organization (WIPO)',
    framework: 'Budapest Treaty on the International Recognition of the Deposit of Microorganisms for the Purposes of Patent Procedure (1977, amended 1980)',
    section: 'Articles 3, 4, 5, 6 & 7',
    jurisdiction: 'INTERNATIONAL',
    title: 'International Microorganism Deposit for Patent Disclosure in Fermented Ayurvedic Preparations',
    passage: 'The Budapest Treaty provides that a single deposit of a microorganism with an International Depositary Authority (IDA) suffices for patent filing purposes across all contracting states (currently 87 member states including India via the Microbial Type Culture Collection MTCC, Chandigarh and Institute of Microbial Technology IMTECH). For Ayurvedic fermented preparations (Asava and Arishta), novel probiotic formulations, and microbial biotransformation processes, the deposit of specific starter cultures, fermentation-active yeast strains (e.g. Saccharomyces cerevisiae variants used in Dhataki-based Sandhana Kalpana), or engineered microbial consortia is mandatory when the microorganism cannot be adequately described in the patent specification alone. Article 6 guarantees sample furnishing to authorized parties during patent examination. Indian IDAs: MTCC (CSIR-IMTECH, Chandigarh) and MCC (National Centre for Microbial Resource, Pune).',
    strength: 'HIGH',
    sourceUrl: 'https://www.wipo.int/wipolex/en/treaties/textdetails/en/treaties/18/budapest',
    pageNumber: 1,
    pageRecord: 'Budapest Treaty 1977, Articles 3-7',
    verificationStatus: 'VERIFIED_OFFICIAL',
    version: 'Budapest Treaty 1977 (amended September 26, 1980)',
    effectiveDate: '2001-12-17',
    tags: ['international', 'budapest treaty', 'microorganism', 'deposit', 'fermentation', 'asava', 'arishta', 'patent']
  }
];

// =========================================================================
// 10 END-TO-END DEMO SCENARIOS COVERING ALL STATUTORY REGIMES
// =========================================================================
export const DEMO_SCENARIOS: Product[] = [
  // Scenario 1: Ashwagandha + Turmeric Joint Support (Patent & Proprietary ASU)
  {
    id: 'prod-ashwa-joint-001',
    name: 'Ashwagandha & Haridra Joint Relief Synergy',
    brandName: 'ArthriSakti Pro',
    description: 'Synergistic formulation combining standardized hydroalcoholic Ashwagandha root extract and supercritical CO2 Curcuma longa extract with bioenhancing Piper longum.',
    intendedUse: 'Musculoskeletal comfort and healthy joint mobility support.',
    healthClaims: [
      'Promotes healthy joint mobility and comfort',
      'Supports natural anti-inflammatory response without gastric irritation'
    ],
    dosageForm: 'CAPSULE',
    ingredients: [
      {
        sanskritName: 'Ashwagandha',
        commonName: 'Indian Ginseng',
        botanicalName: 'Withania somnifera (L.) Dunal',
        plantPart: 'Root',
        ratio: '5:1 extract',
        concentration: '250mg (standardized to 5% withanolides)',
        extractionMethod: 'Hydroalcoholic extraction (50:50 water/ethanol)',
        pharmacopoeiaRef: 'API Part I, Vol. I, pg 19',
        traditionalRef: 'Charaka Samhita Chikitsasthana 1 (Rasayana)',
        tkdlFlag: true,
        isClassicalMatch: false
      },
      {
        sanskritName: 'Haridra',
        commonName: 'Turmeric',
        botanicalName: 'Curcuma longa L.',
        plantPart: 'Rhizome',
        ratio: '10:1 extract',
        concentration: '200mg (standardized to 95% curcuminoids)',
        extractionMethod: 'Supercritical CO2 fluid extraction',
        pharmacopoeiaRef: 'API Part I, Vol. I, pg 45',
        traditionalRef: 'Charaka Samhita Sutrasthana 4 (Shothahara)',
        tkdlFlag: true,
        isClassicalMatch: false
      },
      {
        sanskritName: 'Pippali',
        commonName: 'Long Pepper',
        botanicalName: 'Piper longum L.',
        plantPart: 'Dried Spikes',
        ratio: 'Crude powder',
        concentration: '25mg (standardized to 1.5% piperine)',
        extractionMethod: 'Micronized fine powder (Mesh 120)',
        pharmacopoeiaRef: 'API Part I, Vol. IV, pg 91',
        traditionalRef: 'Sharangadhara Samhita (Yogavahi / Bioenhancer)',
        tkdlFlag: true,
        isClassicalMatch: false
      }
    ],
    applicantType: 'INDIAN_MSME',
    resourceSource: 'CULTIVATED',
    stateJurisdiction: 'Madhya Pradesh',
    hasForeignEquity: false,
    hasNovelProcess: true,
    isClassicalTextBased: false,
    classicalTextReference: 'Ingredients in 1st Schedule texts, but combination & supercritical CO2 extract ratio are proprietary',
    classification: 'PATENT_PROPRIETARY',
    classificationRationale: 'Ingredients exist in First Schedule Ayurvedic texts (API), but the specific synergistic ratio and supercritical extraction represent a Patent/Proprietary (P&P) ASU formulation under Section 3(h) of Drugs & Cosmetics Act.',
    targetExportMarket: 'USA',
    status: 'ASSESSED',
    createdAt: '2026-09-01T10:00:00.000Z',
    updatedAt: '2026-09-05T08:00:00.000Z'
  },

  // Scenario 2: Classical Yogaraja Guggulu (Classical Generic ASU)
  {
    id: 'prod-classical-yogaraja-002',
    name: 'Classical Yogaraja Guggulu Vati',
    brandName: 'Shuddha Ayurveda Yogaraja',
    description: 'Authentic classical generic tablet prepared strictly in accordance with Bhaishajya Ratnavali (Amavata Rogadhikara) using purified Commiphora mukul and classical co-ingredients.',
    intendedUse: 'Alleviation of Amavata (joint stiffness), Sandhivata, and neuromuscular imbalances.',
    healthClaims: [
      'Classical Ayurvedic therapeutic yoga for deep Vata-Kapha cleansing',
      'Relief in joint stiffness as documented in Bhaishajya Ratnavali'
    ],
    dosageForm: 'VATI',
    ingredients: [
      {
        sanskritName: 'Guggulu',
        commonName: 'Indian Bdellium',
        botanicalName: 'Commiphora mukul (Stocks) Hook.',
        plantPart: 'Purified Oleo-gum-resin',
        ratio: 'Classical Shodhana in Triphala Kwatha',
        concentration: '250mg',
        extractionMethod: 'Classical Shodhana & Ghana preparation',
        pharmacopoeiaRef: 'API Part I, Vol. I, pg 43',
        traditionalRef: 'Bhaishajya Ratnavali Amavata Rogadhikara 90-95',
        tkdlFlag: true,
        isClassicalMatch: true
      },
      {
        sanskritName: 'Haritaki',
        commonName: 'Chebulic Myrobalan',
        botanicalName: 'Terminalia chebula Retz.',
        plantPart: 'Fruit pericarp',
        ratio: 'Classical formula part',
        concentration: '50mg',
        extractionMethod: 'Fine powder as per classical text',
        pharmacopoeiaRef: 'API Part I, Vol. I, pg 47',
        traditionalRef: 'Bhaishajya Ratnavali Amavata Rogadhikara',
        tkdlFlag: true,
        isClassicalMatch: true
      }
    ],
    applicantType: 'INDIVIDUAL',
    resourceSource: 'TRADER_SUPPLIED',
    stateJurisdiction: 'Kerala',
    hasForeignEquity: false,
    hasNovelProcess: false,
    isClassicalTextBased: true,
    classicalTextReference: 'Bhaishajya Ratnavali, Chapter on Amavata Rogadhikara (Verse 90-95)',
    classification: 'CLASSICAL_GENERIC',
    classificationRationale: 'Formulation, processing methods, and indication are verbatim from First Schedule classical text (Bhaishajya Ratnavali). Subject to Section 3(p) patent bar; clinical trials exempt under Rule 158-B(I).',
    targetExportMarket: 'EU',
    status: 'ASSESSED',
    createdAt: '2026-09-01T11:00:00.000Z',
    updatedAt: '2026-09-05T08:00:00.000Z'
  },

  // Scenario 3: Ojas Rasayana Granules (Ayurveda Aahar - FSSAI Regime)
  {
    id: 'prod-ojas-aahar-003',
    name: 'Ojas Rasayana Ayurveda Aahar Granules',
    brandName: 'PranaVital Aahar',
    description: 'Nourishing daily dietary granules made with Amalaki, Shatavari, and Yashtimadhu in a cow ghee and organic jaggery base, formulated under FSSAI Ayurveda Aahar Regulations 2022.',
    intendedUse: 'Daily nutritional support for vigor, immunity, and physiological homeostasis.',
    healthClaims: [
      'Promotes natural vitality and daily stamina (Rasayana)',
      'Supports healthy digestion and nutrient assimilation'
    ],
    dosageForm: 'AAHAR_BAR',
    ingredients: [
      {
        sanskritName: 'Amalaki',
        commonName: 'Indian Gooseberry',
        botanicalName: 'Phyllanthus emblica L.',
        plantPart: 'Fresh Fruit Pericarp',
        ratio: 'Avaleha preparation in Ghee',
        concentration: '500mg',
        extractionMethod: 'Classical Svarasa swarupa cooking',
        pharmacopoeiaRef: 'API Part I, Vol. I, pg 5',
        traditionalRef: 'Charaka Samhita Chikitsasthana 1 (Rasayana Pada)',
        tkdlFlag: true,
        isClassicalMatch: false
      },
      {
        sanskritName: 'Shatavari',
        commonName: 'Wild Asparagus',
        botanicalName: 'Asparagus racemosus Willd.',
        plantPart: 'Tuberous Root',
        ratio: 'Standardized crude powder',
        concentration: '300mg',
        extractionMethod: 'Sun-dried and pulverized (Mesh 80)',
        pharmacopoeiaRef: 'API Part I, Vol. IV, pg 108',
        traditionalRef: 'Charaka Samhita Sutrasthana 4 (Balya Mahakashaya)',
        tkdlFlag: true,
        isClassicalMatch: false
      }
    ],
    applicantType: 'INDIAN_MSME',
    resourceSource: 'CULTIVATED',
    stateJurisdiction: 'Gujarat',
    hasForeignEquity: false,
    hasNovelProcess: false,
    isClassicalTextBased: false,
    classicalTextReference: 'FSSAI Ayurveda Aahar Schedule I ingredients used in dietary confectionery format',
    classification: 'AYURVEDA_AAHAR',
    classificationRationale: 'Formulated strictly as a dietary food under Food Safety and Standards (Ayurveda Aahar) Regulations, 2022. Absolute prohibition on disease mitigation/treatment claims under FSSAI Reg. 4 and DMR Act.',
    targetExportMarket: 'USA',
    status: 'ASSESSED',
    createdAt: '2026-09-02T10:00:00.000Z',
    updatedAt: '2026-09-05T08:00:00.000Z'
  },

  // Scenario 4: Standardized Withanolide Phytopharmaceutical (DCGI Pathway)
  {
    id: 'prod-phyto-withan-004',
    name: 'Standardized Withanolide Phytopharmaceutical Extract (WS-Phyto-4)',
    brandName: 'NeuroWithan PhytoRx',
    description: 'Purified and standardized fraction of Withania somnifera containing 4 quantified chemical biomarkers (Withaferin A, Withanolide A, Withanolide B, and 12-Deoxywithastramonolide).',
    intendedUse: 'Prescription botanical drug for cognitive recovery and neuroprotective adjunctive therapy.',
    healthClaims: [
      'Standardized neuro-regenerative activity with minimum 4 active chemical markers',
      'Demonstrated preclinical safety dossier compliant with CDSCO Schedule Y Appendix I-B'
    ],
    dosageForm: 'CAPSULE',
    ingredients: [
      {
        sanskritName: 'Ashwagandha',
        commonName: 'Indian Ginseng',
        botanicalName: 'Withania somnifera (L.) Dunal',
        plantPart: 'Root',
        ratio: 'Purified chromatographic fraction',
        concentration: '150mg (min 4 marker fingerprint)',
        extractionMethod: 'Targeted column chromatography fractionation',
        pharmacopoeiaRef: 'IP 2022 Phytopharmaceutical Monograph Draft',
        traditionalRef: 'First Schedule texts cite raw herb; purified 4-marker fraction is a modern phytopharmaceutical',
        tkdlFlag: false,
        isClassicalMatch: false
      }
    ],
    applicantType: 'INDIAN_BUSINESS',
    resourceSource: 'CULTIVATED',
    stateJurisdiction: 'Maharashtra',
    hasForeignEquity: false,
    hasNovelProcess: true,
    isClassicalTextBased: false,
    classicalTextReference: 'Not a classical yoga; purified fraction governed under CDSCO Rule 122-E',
    classification: 'PHYTOPHARMACEUTICAL',
    classificationRationale: 'Purified and standardized botanical fraction with 4 defined bioactive markers. Evaluated by DCGI under Drugs and Cosmetics Rules Rule 122-E & Schedule Y Appendix I-B requiring Phase I-III clinical trials.',
    targetExportMarket: 'USA',
    status: 'ASSESSED',
    createdAt: '2026-09-02T14:00:00.000Z',
    updatedAt: '2026-09-05T08:00:00.000Z'
  },

  // Scenario 5: Synthetic Nootropic (Out of Corpus Safe Abstention Trigger)
  {
    id: 'prod-synthetic-nootropic-005',
    name: 'Synthetic Piracetam Derivative Nootropic (2-Oxopyrrolidine)',
    brandName: 'SynaptiChem-X',
    description: 'Wholly laboratory-synthesized chemical compound structurally related to piracetam with zero botanical or traditional Ayurvedic origin.',
    intendedUse: 'Synthetic cognitive enhancement via synthetic neurotransmitter modulation.',
    healthClaims: [
      'Chemical receptor agonism',
      'Laboratory synthetic nootropic'
    ],
    dosageForm: 'CAPSULE',
    ingredients: [
      {
        sanskritName: 'None (Synthetic)',
        commonName: 'Synthetic Piracetam Analog',
        botanicalName: 'N/A (Synthetic Chemical Molecule)',
        plantPart: 'Synthetic chemical synthesis',
        ratio: 'Pure molecule',
        concentration: '400mg',
        extractionMethod: 'Organic chemical synthesis',
        pharmacopoeiaRef: 'Not in API or First Schedule Ayurvedic texts',
        traditionalRef: 'None',
        tkdlFlag: false,
        isClassicalMatch: false
      }
    ],
    applicantType: 'INDIAN_BUSINESS',
    resourceSource: 'TRADER_SUPPLIED',
    stateJurisdiction: 'Karnataka',
    hasForeignEquity: false,
    hasNovelProcess: false,
    isClassicalTextBased: false,
    classicalTextReference: 'None - purely synthetic pharmaceutical molecule',
    classification: 'UNCERTAIN',
    classificationRationale: 'Non-Ayurvedic synthetic chemical substance. System triggers Safe AI Abstention since synthetic small molecules fall completely outside the statutory remit of the Ministry of Ayush.',
    targetExportMarket: 'USA',
    status: 'PENDING_REVIEW',
    createdAt: '2026-09-03T09:00:00.000Z',
    updatedAt: '2026-09-05T08:00:00.000Z'
  },

  // Scenario 6: Classical Triphala Churna (Trademark Descriptive Bar Demo)
  {
    id: 'prod-triphala-churna-006',
    name: 'Classical Triphala Churna',
    brandName: 'Triphala Pure',
    description: 'Time-honored classical generic powder prepared by blending equal parts of Haritaki, Bibhitaki, and Amalaki as prescribed in Sharangadhara Samhita.',
    intendedUse: 'Classical digestive balancing, mild laxative action (Anulomana), and eye health support (Chakshushya).',
    healthClaims: [
      'Classical Tridosha balancing formula documented in Sharangadhara Samhita',
      'Supports natural daily bowel regulation and ocular vigor'
    ],
    dosageForm: 'CHURNA',
    ingredients: [
      {
        sanskritName: 'Haritaki',
        commonName: 'Chebulic Myrobalan',
        botanicalName: 'Terminalia chebula Retz.',
        plantPart: 'Fruit Pericarp',
        ratio: '1 part',
        concentration: '333mg',
        extractionMethod: 'Micronized fine powder (Mesh 100)',
        pharmacopoeiaRef: 'API Part I, Vol. I, pg 47',
        traditionalRef: 'Sharangadhara Samhita Madhyama Khanda 6',
        tkdlFlag: true,
        isClassicalMatch: true
      },
      {
        sanskritName: 'Bibhitaki',
        commonName: 'Belleric Myrobalan',
        botanicalName: 'Terminalia bellirica (Gaertn.) Roxb.',
        plantPart: 'Fruit Pericarp',
        ratio: '1 part',
        concentration: '333mg',
        extractionMethod: 'Micronized fine powder (Mesh 100)',
        pharmacopoeiaRef: 'API Part I, Vol. I, pg 26',
        traditionalRef: 'Sharangadhara Samhita Madhyama Khanda 6',
        tkdlFlag: true,
        isClassicalMatch: true
      },
      {
        sanskritName: 'Amalaki',
        commonName: 'Emblic Myrobalan',
        botanicalName: 'Phyllanthus emblica L.',
        plantPart: 'Fruit Pericarp',
        ratio: '1 part',
        concentration: '334mg',
        extractionMethod: 'Micronized fine powder (Mesh 100)',
        pharmacopoeiaRef: 'API Part I, Vol. I, pg 5',
        traditionalRef: 'Sharangadhara Samhita Madhyama Khanda 6',
        tkdlFlag: true,
        isClassicalMatch: true
      }
    ],
    applicantType: 'INDIAN_MSME',
    resourceSource: 'TRADER_SUPPLIED',
    stateJurisdiction: 'Rajasthan',
    hasForeignEquity: false,
    hasNovelProcess: false,
    isClassicalTextBased: true,
    classicalTextReference: 'Sharangadhara Samhita, Madhyama Khanda, Adhyaya 6 (Verse 8-10)',
    classification: 'CLASSICAL_GENERIC',
    classificationRationale: 'Exact classical generic formulation from First Schedule text. Trademark "Triphala Pure" triggers Section 9(1)(b) descriptive mark refusal under Trade Marks Act 1999; patent barred under Section 3(p).',
    targetExportMarket: 'UK',
    status: 'ASSESSED',
    createdAt: '2026-09-03T12:00:00.000Z',
    updatedAt: '2026-09-05T08:00:00.000Z'
  },

  // Scenario 7: Supercritical CO2 Neem Extract (Process Patent Route Demo)
  {
    id: 'prod-neem-extract-007',
    name: 'Supercritical CO2 Nimba (Neem) Bioactive Extract',
    brandName: 'AzadaPur CO2',
    description: 'Proprietary supercritical CO2 extract of Azadirachta indica seed kernels at 320 bar and 45°C yielding high azadirachtin-A and nimbin content without toxic organic solvent residues.',
    intendedUse: 'Topical antimicrobial application for compromised skin barrier and fungal management.',
    healthClaims: [
      'High-potency green-extracted limonoid fraction free of solvent residues',
      'Supports healthy cutaneous flora and soothing topical comfort'
    ],
    dosageForm: 'TAILA',
    ingredients: [
      {
        sanskritName: 'Nimba',
        commonName: 'Neem',
        botanicalName: 'Azadirachta indica A. Juss.',
        plantPart: 'Seed Kernel',
        ratio: 'Supercritical CO2 fluid extract',
        concentration: '5% active liminoids',
        extractionMethod: 'Closed-loop scCO2 at 320 bar, 45°C with cosolvent ethanol 2%',
        pharmacopoeiaRef: 'API Part I, Vol. II, pg 130',
        traditionalRef: 'Charaka Samhita Sutrasthana 4 (Kandughna Mahakashaya)',
        tkdlFlag: true,
        isClassicalMatch: false
      }
    ],
    applicantType: 'INDIAN_MSME',
    resourceSource: 'CULTIVATED',
    stateJurisdiction: 'Tamil Nadu',
    hasForeignEquity: false,
    hasNovelProcess: true,
    isClassicalTextBased: false,
    classicalTextReference: 'Neem is a First Schedule herb; proprietary scCO2 extraction parameters are novel',
    classification: 'PATENT_PROPRIETARY',
    classificationRationale: 'While Neem is traditional knowledge (Section 3(p)), the specific supercritical CO2 process parameters (pressure, temperature, cosolvent ratio) qualify for Process Patent claims under Patents Act 1970.',
    targetExportMarket: 'USA',
    status: 'ASSESSED',
    createdAt: '2026-09-03T15:00:00.000Z',
    updatedAt: '2026-09-05T08:00:00.000Z'
  },

  // Scenario 8: Cultivated Guduchi Immunity Tablet (Section 7 BDA Cultivator Exemption)
  {
    id: 'prod-guduchi-cultivated-008',
    name: 'Cultivated Guduchi (Giloy) Ghana Tablet',
    brandName: 'AmritaLife Pure',
    description: 'Standardized aqueous dry extract (Ghana) of Tinospora cordifolia stems sourced entirely from GAP-certified cultivated farmlands with verifiable chain-of-custody certificates.',
    intendedUse: 'Immunomodulatory support (Rasayana) and cellular antioxidant defense.',
    healthClaims: [
      'Supports natural innate immunity and optimal liver function',
      'Classical aqueous Ghana extract with standardized bitter glycosides'
    ],
    dosageForm: 'VATI',
    ingredients: [
      {
        sanskritName: 'Guduchi',
        commonName: 'Heart-leaved Moonseed',
        botanicalName: 'Tinospora cordifolia (Willd.) Miers',
        plantPart: 'Mature Stem',
        ratio: '10:1 aqueous Ghana extract',
        concentration: '300mg (standardized to 3% bitters)',
        extractionMethod: 'Classical aqueous decoction concentrated to dry extract',
        pharmacopoeiaRef: 'API Part I, Vol. I, pg 34',
        traditionalRef: 'Charaka Samhita Sutrasthana 25 (Vayasthapana Agrya)',
        tkdlFlag: true,
        isClassicalMatch: false
      }
    ],
    applicantType: 'INDIAN_MSME',
    resourceSource: 'CULTIVATED',
    stateJurisdiction: 'Uttar Pradesh',
    hasForeignEquity: false,
    hasNovelProcess: false,
    isClassicalTextBased: false,
    classicalTextReference: 'Single herb Ghana preparation; ingredients in API Part I',
    classification: 'PATENT_PROPRIETARY',
    classificationRationale: 'Formulation uses cultivated Tinospora cordifolia. Under Section 7 Proviso of Biological Diversity (Amendment) Act 2023, cultivated raw materials with valid farmer origin certificates enjoy exemption from prior access levies.',
    targetExportMarket: 'UK',
    status: 'ASSESSED',
    createdAt: '2026-09-04T08:00:00.000Z',
    updatedAt: '2026-09-05T08:00:00.000Z'
  },

  // Scenario 9: Brahmi Neuro Drink with Curative Claims (DMR Act Red Flag Demo)
  {
    id: 'prod-brahmi-drink-009',
    name: 'Brahmi Mind Sharpening Botanical Drink',
    brandName: 'NeuroMax Cure Elixir',
    description: 'Herbal beverage containing Bacopa monnieri juice, Mandukaparni extract, and Shankhapushpi sweetened with raw honey.',
    intendedUse: 'Cognitive enhancement beverage marketed to student and executive demographics.',
    healthClaims: [
      'Permanently cures mental fatigue, insomnia, and early stage Alzheimer dementia',
      'Clinically proven to reverse memory impairment in 30 days'
    ],
    dosageForm: 'SYRUP',
    ingredients: [
      {
        sanskritName: 'Brahmi',
        commonName: 'Water Hyssop',
        botanicalName: 'Bacopa monnieri (L.) Wettst.',
        plantPart: 'Whole Herb',
        ratio: 'Fresh juice (Svarasa)',
        concentration: '20% v/v',
        extractionMethod: 'Cold expression of fresh herb',
        pharmacopoeiaRef: 'API Part I, Vol. II, pg 25',
        traditionalRef: 'Charaka Samhita Chikitsasthana 1 (Medhya Rasayana)',
        tkdlFlag: true,
        isClassicalMatch: false
      },
      {
        sanskritName: 'Shankhapushpi',
        commonName: 'Speedwheel',
        botanicalName: 'Convolvulus pluricaulis Choisy',
        plantPart: 'Whole Plant',
        ratio: 'Aqueous extract',
        concentration: '100mg',
        extractionMethod: 'Hot water decoction',
        pharmacopoeiaRef: 'API Part I, Vol. II, pg 147',
        traditionalRef: 'Charaka Samhita Chikitsasthana 1',
        tkdlFlag: true,
        isClassicalMatch: false
      }
    ],
    applicantType: 'INDIAN_MSME',
    resourceSource: 'CULTIVATED',
    stateJurisdiction: 'Karnataka',
    hasForeignEquity: false,
    hasNovelProcess: false,
    isClassicalTextBased: false,
    classicalTextReference: 'Ingredients in First Schedule; marketed as a consumer beverage',
    classification: 'AYURVEDA_AAHAR',
    classificationRationale: 'Ayurveda Aahar beverage classification. CRITICAL VIOLATION: Health claims mention "cures Alzheimer dementia and insomnia". Under Section 3 of Drugs and Magic Remedies Act 1954, advertising cures for memory/mental disorders is a cognizable criminal offense.',
    targetExportMarket: 'USA',
    status: 'ASSESSED',
    createdAt: '2026-09-04T10:00:00.000Z',
    updatedAt: '2026-09-05T08:00:00.000Z'
  },

  // Scenario 10: European Export Ashwagandha (EU THMPD 15-Year Rule Demo)
  {
    id: 'prod-ashwa-eu-export-010',
    name: 'Ashwagandha Organic Root Extract EU Export Formula',
    brandName: 'VedaEuro Sleep & Vitality',
    description: 'Standardized aqueous extract of Withania somnifera roots prepared for market authorization in Germany and France.',
    intendedUse: 'Adaptogenic relief of mild mental stress, fatigue, and sleep onset assistance.',
    healthClaims: [
      'Traditional herbal remedy for temporary relief of mild symptoms of mental stress',
      'Standardized to withanolides, tested for pesticide and pyrrolizidine alkaloid compliance'
    ],
    dosageForm: 'CAPSULE',
    ingredients: [
      {
        sanskritName: 'Ashwagandha',
        commonName: 'Indian Ginseng',
        botanicalName: 'Withania somnifera (L.) Dunal',
        plantPart: 'Dried Root',
        ratio: '4:1 water extract',
        concentration: '300mg',
        extractionMethod: 'Aqueous decoction followed by vacuum spray drying',
        pharmacopoeiaRef: 'API Part I, Vol. I, pg 19 & European Pharmacopoeia (Ph. Eur.)',
        traditionalRef: 'Charaka Samhita Chikitsasthana 1',
        tkdlFlag: true,
        isClassicalMatch: false
      }
    ],
    applicantType: 'INDIAN_BUSINESS',
    resourceSource: 'CULTIVATED',
    stateJurisdiction: 'Madhya Pradesh',
    hasForeignEquity: false,
    hasNovelProcess: false,
    isClassicalTextBased: false,
    classicalTextReference: 'Single botanical extract intended for European herbal registration',
    classification: 'PATENT_PROPRIETARY',
    classificationRationale: 'Targeting European Union registration. Under EU Directive 2004/24/EC (THMPD), simplified herbal registration requires 30-year traditional use including at least 15 years within the EU. If lacking EU historical sales, applicant must file under national Food Supplement frameworks instead.',
    targetExportMarket: 'EU',
    status: 'ASSESSED',
    createdAt: '2026-09-04T14:00:00.000Z',
    updatedAt: '2026-09-05T08:00:00.000Z'
  }
];
